---
settings:
  name: Active IQ Unified Manager 9.14
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.14'
    url: "/active-iq-unified-manager"
  - version-number: '9.13'
    url: "/active-iq-unified-manager-913"
  - version-number: '9.12'
    url: "/active-iq-unified-manager-912"
  - version-number: '9.11'
    url: "/active-iq-unified-manager-911"
  - version-number: '9.10'
    url: "/active-iq-unified-manager-910"
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de Active IQ Unified Manager 9,14
    url: "/index.html"
  - title: Notas de la versión
    url: "/reference_release_notes.html"
  - title: Manos a la obra
    entries:
    - title: Instalación rápida para VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Instalación de inicio rápido para Linux
      url: "/install-linux/qsg-linux.html"
    - title: Instalación de inicio rápido para Windows
      url: "/install-windows/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: storage-mgmt
  - section: events
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Avisos legales
    url: "/legal-notices.html"
