---
permalink: api-automation/concept_get_started_with_um_apis.html 
sidebar: sidebar 
keywords: active iq, unified manager 
summary: Active IQ Unified Manager proporciona un conjunto de API para gestionar sus recursos de almacenamiento en los sistemas de almacenamiento compatibles mediante una interfaz de servicio web RESTful para cualquier integración de terceros. 
---
= Primeros pasos con API de REST de Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager proporciona un conjunto de API para gestionar sus recursos de almacenamiento en los sistemas de almacenamiento compatibles mediante una interfaz de servicio web RESTful para cualquier integración de terceros.

En estos temas, encontrará información sobre las API de Unified Manager, flujos de trabajo de muestra para resolver problemas específicos y algunos códigos de muestra. Mediante esta información, puede crear clientes RESTful de soluciones de software de gestión de NetApp para gestionar sistemas NetApp. Las API se basan en el estilo arquitectónico de transferencia de estado representacional (REST). Se admiten las cuatro operaciones REST Create, Read, Update y Delete (también llamadas CRUD).
