---
permalink: api-automation/concept_verify_svm_workflow.html 
sidebar: sidebar 
keywords: verify, svms, clusters 
summary: 'Antes de aprovisionar recursos compartidos de archivos o LUN, debe comprobar si los clústeres tienen máquinas virtuales de almacenamiento (SVM) creadas en ellos.' 
---
= Verificación de las SVM en clústeres mediante API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de aprovisionar recursos compartidos de archivos o LUN, debe comprobar si los clústeres tienen máquinas virtuales de almacenamiento (SVM) creadas en ellos.

[NOTE]
====
En el flujo de trabajo se supone que los clústeres de ONTAP se añadieron a Unified Manager y se ha obtenido la clave de clúster. Los clústeres deben tener las licencias necesarias para aprovisionar LUN y recursos compartidos de archivos en ellos.

====
. Comprobar si el clúster tiene una SVM creada.
+
[cols="3*"]
|===
| Categoría | Verbo HTTP | Ruta 


 a| 
centro de datos
 a| 
OBTENGA
 a| 
`/datacenter/svm/svms`
`/datacenter/svm/svms/\{key}`

|===
+
*Muestra de rizo*

+
[listing]
----
curl -X GET "https://<hostname>/api/datacenter/svm/svms" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
. Si no devuelve la clave SVM, cree la SVM. Para crear las SVM, debe contar con la clave de clúster en la que aprovisiona la SVM. También debe especificar el nombre de la SVM. Siga estos pasos.
+
[cols="3*"]
|===
| Categoría | Verbo HTTP | Ruta 


 a| 
centro de datos
 a| 
OBTENGA
 a| 
`/datacenter/cluster/clusters`
`/datacenter/cluster/clusters/\{key}`

|===
+
Obtenga la clave de clúster.

+
*Muestra de rizo*

+
[listing]
----
curl -X GET "https://<hostname>/api/datacenter/cluster/clusters" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
. En el resultado, obtenga la clave de clúster y después utilícela como entrada para crear la SVM.
+
[NOTE]
====
Al crear la SVM, asegúrese de que sea compatible con todos los protocolos necesarios para aprovisionar las LUN y recursos compartidos de archivos en ellas, por ejemplo, CIFS, NFS, FCP, E iSCSI. Es posible que se produzca un error en los flujos de trabajo de aprovisionamiento si la SVM no admite los servicios necesarios. Es recomendable que los servicios para los respectivos tipos de cargas de trabajo estén habilitados en la SVM.

====
+
[cols="3*"]
|===
| Categoría | Verbo HTTP | Ruta 


 a| 
centro de datos
 a| 
PUBLICAR
 a| 
`/datacenter/svm/svms`

|===
+
*Muestra de rizo*

+
Introduzca los detalles del objeto de SVM como parámetros de entrada.

+
[listing]
----
curl -X POST "https://<hostname>/api/datacenter/svm/svms" -H "accept: application/json" -H "Content-Type: application/json" -H "Authorization: Basic <Base64EncodedCredentials>" "{ \"aggregates\": [ { \"_links\": {}, \"key\": \"1cd8a442-86d1,type=objecttype,uuid=1cd8a442-86d1-11e0-ae1c-9876567890123\",
\"name\": \"cluster2\", \"uuid\": \"02c9e252-41be-11e9-81d5-00a0986138f7\" } ],
\"cifs\": { \"ad_domain\": { \"fqdn\": \"string\", \"password\": \"string\",
\"user\": \"string\" }, \"enabled\": true, \"name\": \"CIFS1\" },
\"cluster\": { \"key\": \"1cd8a442-86d1-11e0-ae1c-123478563412,type=object type,uuid=1cd8a442-86d1-11e0-ae1c-9876567890123\" },
\"dns\": { \"domains\": [ \"example.com\", \"example2.example3.com\" ],
\"servers\": [ \"10.224.65.20\", \"2001:db08:a0b:12f0::1\" ] },
\"fcp\": { \"enabled\": true }, \"ip_interface\": [ { \"enabled\": true,
\"ip\": { \"address\": \"10.10.10.7\", \"netmask\": \"24\" },
\"location\": { \"home_node\": { \"name\": \"node1\" } }, \"name\":
\"dataLif1\" } ], \"ipspace\": { \"name\": \"exchange\" },
\"iscsi\": { \"enabled\": true }, \"language\": \"c.utf_8\",
\"ldap\": { \"ad_domain\": \"string\", \"base_dn\": \"string\",
\"bind_dn\": \"string\", \"enabled\": true, \"servers\": [ \"string\" ] },
\"name\": \"svm1\", \"nfs\": { \"enabled\": true },
\"nis\": { \"domain\": \"string\", \"enabled\": true,
\"servers\": [ \"string\" ] }, \"nvme\": { \"enabled\": true },
\"routes\": [ { \"destination\": { \"address\": \"10.10.10.7\",
\"netmask\": \"24\" }, \"gateway\": \"string\" } ],
\"snapshot_policy\": { \"name\": \"default\" },
\"state\": \"running\", \"subtype\": \"default\"}"
----
+
El resultado de JSON muestra una clave de objeto de Job que puede utilizar para verificar la SVM que ha creado.

. Compruebe la creación de la SVM mediante la clave de objeto de trabajo a consultar. Si la SVM se crea correctamente, se devuelve la clave SVM en la respuesta.
+
[cols="3*"]
|===
| Categoría | Verbo HTTP | Ruta 


 a| 
servidor de gestión
 a| 
OBTENGA
 a| 
`/management-server/jobs/\{key}`

|===

