---
permalink: reporting/generaltask_um_rest_apis_that_can_be_used_for_reporting.html 
sidebar: sidebar 
keywords: unified manager ,rest api, reporting 
summary: Puede usar API REST para ayudar a gestionar los clústeres mediante la visualización de la información de estado, capacidad, rendimiento y seguridad capturada por Unified Manager. 
---
= Las API DE REST de Unified Manager que se pueden usar para crear informes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar API REST para ayudar a gestionar los clústeres mediante la visualización de la información de estado, capacidad, rendimiento y seguridad capturada por Unified Manager.

Las API DE REST se exponen a través de la página web de Swagger. Es posible acceder a la página web de Swagger para ver la documentación de la API DE REST de Unified Manager, y también para emitir manualmente una llamada API. En la interfaz de usuario web de Unified Manager, en la barra de menús, haga clic en el botón *Ayuda* y seleccione *Documentación de API*. Para obtener información sobre las API DE REST de Unified Manager, consulte link:../api-automation/concept_get_started_with_um_apis.html["Primeros pasos con API de REST de Active IQ Unified Manager"].

Debe tener el rol de operador, administrador de almacenamiento o administrador de aplicaciones para acceder a las API DE REST.
