---
permalink: performance-checker/concept_performance_monitor_of_metrocluster_configurations.html 
sidebar: sidebar 
keywords: performance, monitor, metrocluster, throughput 
summary: Unified Manager permite supervisar el rendimiento de escritura entre clústeres en una configuración de MetroCluster para identificar cargas de trabajo con un alto nivel de rendimiento de escritura. Si estas cargas de trabajo de alto rendimiento hacen que otros volúmenes en el clúster local tengan tiempos de respuesta de I/o elevados, Unified Manager activa los eventos de rendimiento para notificarle. 
---
= Supervisión del rendimiento de las configuraciones de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager permite supervisar el rendimiento de escritura entre clústeres en una configuración de MetroCluster para identificar cargas de trabajo con un alto nivel de rendimiento de escritura.

Si estas cargas de trabajo de alto rendimiento hacen que otros volúmenes en el clúster local tengan tiempos de respuesta de I/o elevados, Unified Manager activa los eventos de rendimiento para notificarle.


NOTE: Unified Manager trata los clústeres de una configuración de MetroCluster como clústeres individuales. No distingue entre clústeres que son partners ni relaciona el rendimiento de escritura de cada clúster.

Cuando un clúster local en una configuración MetroCluster refleja sus datos en el clúster del partner, los datos se escriben en NVRAM y, después, se transfieren mediante los vínculos interswitch (ISL) a los agregados remotos. Unified Manager analiza la NVRAM para identificar las cargas de trabajo cuyo alto rendimiento de escritura está utilizando demasiado la NVRAM, poniendo en contención a la NVRAM.

Las cargas de trabajo cuya desviación en el tiempo de respuesta ha superado el umbral de rendimiento se denominan _víctimas_ y las cargas de trabajo cuya desviación en el rendimiento de escritura en la NVRAM es mayor de lo habitual, lo que provoca la contención, se denominan _abusones_. Dado que solo se reflejan las solicitudes de escritura en el clúster de partners, Unified Manager no analiza el rendimiento de lectura.

Puede ver el rendimiento de cualquiera de los clústeres de una configuración de MetroCluster analizando las cargas de trabajo de los LUN y volúmenes correspondientes desde las siguientes pantallas. Puede filtrar los resultados por el clúster. Desde el panel de navegación de la izquierda:

* *Almacenamiento > clústeres > rendimiento: Vista todos los clústeres*. Consulte
* *Almacenamiento > volúmenes > rendimiento: Vista todos los volúmenes*.
* *Almacenamiento > LUN > rendimiento: Vista de todas las LUN*.
* *Análisis de cargas de trabajo > todas las cargas de trabajo*


*Información relacionada*

link:../performance-checker/reference_performance_event_analysis_and_notification.html["Análisis y notificación de eventos de rendimiento"]

link:../performance-checker/concept_performance_incident_analysis_for_metrocluster_configuration.html["Análisis de eventos de rendimiento para una configuración de MetroCluster"]

link:../performance-checker/concept_roles_of_workloads_involved_in_performance_incident.html["Funciones de las cargas de trabajo involucradas en un evento de rendimiento"]

link:../performance-checker/task_identify_victim_workloads_involved_in_performance_event.html["Identificar las cargas de trabajo de las víctimas involucradas en un evento de rendimiento"]

link:../performance-checker/task_identify_bully_workloads_involved_in_performance_event.html["Identificar las cargas de trabajo abusivas que están involucradas en un evento de rendimiento"]

link:../performance-checker/task_identify_shark_workloads_involved_in_performance_event.html["Identificar las cargas de trabajo de tiburones en un evento de rendimiento"]
