---
permalink: performance-checker/concept_navigate_performance_workflows_in_unified_manager_ui.html 
sidebar: sidebar 
keywords: navigating, performance, workflows, unified manager, gui 
summary: La interfaz de Unified Manager proporciona muchas páginas para la recogida y visualización de información de rendimiento. Utilice el panel de navegación izquierdo para desplazarse a las páginas de la GUI y utilice fichas y vínculos de las páginas para ver y configurar información. 
---
= Navegar por los flujos de trabajo de rendimiento en la interfaz gráfica de usuario de Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La interfaz de Unified Manager proporciona muchas páginas para la recogida y visualización de información de rendimiento. Utilice el panel de navegación izquierdo para desplazarse a las páginas de la GUI y utilice fichas y vínculos de las páginas para ver y configurar información.

Se utilizan todas las siguientes páginas para supervisar y solucionar problemas con la información de rendimiento del clúster:

* consola
* páginas de inventario de objetos de red y almacenamiento
* páginas de detalles de objetos de almacenamiento (incluido el explorador de rendimiento)
* páginas de configuración y configuración
* páginas de eventos

