---
permalink: performance-checker/concept_how_storage_qos_can_control_workload_throughput.html 
sidebar: sidebar 
keywords: storage, qos, control, workload, throughput 
summary: 'Puede crear un grupo de políticas de calidad de servicio (QoS) para controlar el límite de I/o por segundo (IOPS) o rendimiento (MB/s) para las cargas de trabajo que contiene. Si las cargas de trabajo se encuentran en un grupo de políticas sin un límite establecido, como el grupo de políticas predeterminado, o el límite establecido no cumple con sus necesidades, puede aumentar el límite o mover las cargas de trabajo a un grupo de políticas nuevo o existente que tenga el límite deseado.' 
---
= Cómo la calidad de servicio de almacenamiento puede controlar el rendimiento de la carga de trabajo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede crear un grupo de políticas de calidad de servicio (QoS) para controlar el límite de I/o por segundo (IOPS) o rendimiento (MB/s) para las cargas de trabajo que contiene. Si las cargas de trabajo se encuentran en un grupo de políticas sin un límite establecido, como el grupo de políticas predeterminado, o el límite establecido no cumple con sus necesidades, puede aumentar el límite o mover las cargas de trabajo a un grupo de políticas nuevo o existente que tenga el límite deseado.

Los grupos de políticas de calidad de servicio «¿tradicional» se pueden asignar a cargas de trabajo individuales; por ejemplo, un volumen o una LUN únicos. En este caso, la carga de trabajo puede utilizar el límite de rendimiento completo. También se pueden asignar grupos de políticas de calidad de servicio a varias cargas de trabajo; en cuyo caso, el límite de rendimiento es «esencial» entre las cargas de trabajo. Por ejemplo, un límite de calidad de servicio de 9,000 IOPS asignadas a tres cargas de trabajo restringiría el número de IOPS combinadas de más de 9,000 IOPS.

Los grupos de políticas de calidad de servicio «adaptativas» también pueden asignarse a cargas de trabajo individuales o a varias cargas de trabajo. Sin embargo, incluso cuando se asignan a varias cargas de trabajo, cada carga de trabajo obtiene el límite de rendimiento completo en lugar de compartir el valor de rendimiento con otras cargas de trabajo. Además, las políticas de calidad de servicio adaptativas ajustan automáticamente el valor de rendimiento en función del tamaño del volumen, por carga de trabajo, de modo que se mantenga la ratio de IOPS por terabytes a medida que cambie el tamaño del volumen. Por ejemplo, si el pico se establece en 5,000 IOPS/TB en una política de calidad de servicio adaptativa, un volumen de 10 TB tendrá un rendimiento máximo de 50,000 IOPS. Si el tamaño del volumen cambia más adelante a 20 TB, la calidad de servicio adaptativa ajusta el máximo a 100,000 IOPS.

A partir de ONTAP 9.5, se puede incluir el tamaño de bloque al definir una política de calidad de servicio adaptativa. Esto convierte de forma efectiva la política de un umbral IOPS/TB a un umbral de MB/s para casos en los que las cargas de trabajo utilizan tamaños de bloque muy grandes y, en última instancia, utilizan un gran porcentaje de rendimiento.

En el caso de las políticas de calidad de servicio de los grupos compartidos, cuando las IOPS o MB/s de todas las cargas de trabajo de un grupo de políticas superan el límite establecido, el grupo de políticas limita las cargas de trabajo para restringir su actividad, lo que puede reducir el rendimiento de todas las cargas de trabajo del grupo de políticas. Si la limitación de grupo de políticas genera un evento de rendimiento dinámico, la descripción del evento muestra el nombre del grupo de políticas implicado.

En la vista rendimiento: Todos los volúmenes, es posible ordenar los volúmenes afectados por IOPS y MB/s para ver qué cargas de trabajo tienen el uso más alto que puede haber contribuido al evento. En la página Performance/Volumes Explorer, puede seleccionar otros volúmenes o LUN en el volumen para compararlos con el uso de rendimiento de Mbps o de IOPS de la carga de trabajo afectada.

Al asignar las cargas de trabajo que están utilizando en exceso los recursos del nodo a una configuración de grupo de políticas más restrictiva, el grupo de políticas limita las cargas de trabajo a restringir su actividad, lo que puede reducir el uso de los recursos en ese nodo. Sin embargo, si desea que la carga de trabajo pueda usar más recursos del nodo, puede aumentar el valor del grupo de políticas.

Puede usar System Manager, los comandos de ONTAP o los niveles de servicio de rendimiento de Unified Manager para gestionar grupos de políticas, incluidas las siguientes tareas:

* Crear un grupo de políticas
* Agregar o eliminar cargas de trabajo en un grupo de políticas
* Mover una carga de trabajo entre grupos de políticas
* Cambiar el límite de rendimiento de un grupo de políticas
* Mover una carga de trabajo a otro agregado o nodo

