---
permalink: performance-checker/concept_metrocluster_configuration_verification.html 
sidebar: sidebar 
keywords: metrocluster, configuration, verification 
summary: Puede evitar problemas de rendimiento en las cargas de trabajo reflejadas en una configuración de MetroCluster garantizando que la configuración de MetroCluster se configure correctamente. También puede mejorar el rendimiento de la carga de trabajo cambiando la configuración o actualizando componentes de software o hardware. 
---
= Verificación de la configuración de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede evitar problemas de rendimiento para cargas de trabajo duplicadas en una configuración de MetroCluster over FC e IP, garantizando que la configuración de MetroCluster se configure correctamente. También puede mejorar el rendimiento de la carga de trabajo cambiando la configuración o actualizando componentes de software o hardware.

Consulte https://["Documentación de MetroCluster"] Para obtener las instrucciones de configurar los clústeres en la configuración de MetroCluster, incluidos los switches Fibre Channel (FC), los cables y los enlaces entre switches (ISL). También es útil configurar el software MetroCluster para que los clústeres local y remoto puedan comunicarse con los datos de volúmenes reflejados. Para obtener información específica sobre la configuración de MetroCluster over IP, consulte https://["Instale una configuración de IP de MetroCluster"].

Es posible comparar la configuración de MetroCluster con los requisitos en https://["Documentación de MetroCluster"] Para determinar si cambiar o actualizar componentes de su configuración de MetroCluster puede mejorar el rendimiento de la carga de trabajo. Esta comparación puede ayudarle a responder a las siguientes preguntas:

* ¿Las controladoras son adecuadas para sus cargas de trabajo?
* ¿Necesita actualizar sus paquetes ISL a un ancho de banda mayor para poder gestionar más rendimiento?
* ¿Puede ajustar los créditos de búfer a búfer (BBC) en los switches para aumentar el ancho de banda?
* Si sus cargas de trabajo tienen un rendimiento de escritura elevado para almacenamiento de unidades de estado sólido (SSD), ¿necesita actualizar sus puentes de FC a SAS para adaptarse al rendimiento?


*Información relacionada*

* Para obtener información acerca de cómo reemplazar o actualizar componentes de MetroCluster, consulte https://["Documentación de MetroCluster"].
* Para obtener información sobre la actualización de las controladoras, consulte https://["Actualización de controladoras en una configuración MetroCluster FC mediante conmutación de sitios y conmutación de estado"] y.. https://["Actualización de controladoras en una configuración IP de MetroCluster mediante conmutación de sitios y conmutación de estado"]

