---
permalink: performance-checker/task_edit_user_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: edit, user-defined, performance, threshold, policies 
summary: La configuración del umbral se puede editar para las políticas de umbral de rendimiento existentes. Esto puede ser útil si descubre que está recibiendo demasiadas alertas o muy pocas para ciertas condiciones de umbral. 
---
= Editar políticas de umbral de rendimiento definidas por el usuario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuración del umbral se puede editar para las políticas de umbral de rendimiento existentes. Esto puede ser útil si descubre que está recibiendo demasiadas alertas o muy pocas para ciertas condiciones de umbral.

*Lo que necesitará*

Debe tener la función Administrador de aplicaciones.

No es posible cambiar el nombre de la política ni el tipo de objeto de almacenamiento que se supervisa para las políticas de umbral existentes.

.Pasos
. En el panel de navegación izquierdo, seleccione *umbrales de evento* > *rendimiento*.
+
Se muestra la página Performance Thresholds.

. Seleccione la directiva de umbral que desea cambiar y haga clic en *Editar*.
+
Se muestra la página Edit Performance Threshold Policy.

. Realice los cambios realizados en la directiva de umbral y haga clic en *Guardar*.
+
El resultado es la página Performance Thresholds.



Después de guardar, los cambios se actualizan inmediatamente en todos los objetos de almacenamiento que usan la política.

En función del tipo de cambios realizados en la directiva, es posible que desee revisar la configuración de alerta configurada para los objetos que utilizan la directiva en la página Configuración de alertas.
