---
permalink: storage-mgmt/reference_dashboard_page.html 
sidebar: sidebar 
keywords: dashboard page, 
summary: La página Dashboard tiene “paneles” que muestran el alto nivel de capacidad, rendimiento y estado de seguridad de los clústeres que se están supervisando. Esta página también proporciona un panel Management Actions que enumera las correcciones que Unified Manager puede realizar para resolver ciertos eventos. 
---
= Consola
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La página Dashboard tiene "paneles" que muestran el estado de alta capacidad, rendimiento y seguridad de los clústeres que se supervisan. Esta página también proporciona un panel Management Actions que enumera las correcciones que Unified Manager puede realizar para resolver ciertos eventos.

La mayoría de los paneles también muestran el número de eventos activos de esa categoría y el número de eventos nuevos añadidos a las 24 horas anteriores. Esta información le ayuda a decidir qué clústeres se podrían necesitar para analizar más a fin de resolver eventos. Al hacer clic en los eventos, se muestran los eventos principales y se proporciona un enlace a la página del inventario Event Management filtrada para mostrar los eventos activos de esa categoría.

En la parte superior de la consola puede seleccionar si los paneles muestran información de todos los clústeres supervisados ("todos los clústeres") o de un clúster individual. Para empezar, puede ver el estado de todos los clústeres y profundizar en cada clúster cuando desea ver información detallada.

[NOTE]
====
Algunos de los paneles que se enumeran a continuación aparecen en el panel de control en función de su configuración.

====


== Panel de acciones de gestión

Hay ciertos problemas que Unified Manager puede diagnosticar a fondo y proporcionar una única resolución. Si están disponibles, estas resoluciones se muestran en este panel con un botón *Fix it* o *Fix All*. Es posible solucionar estos problemas inmediatamente desde Unified Manager, en lugar de tener que utilizar ONTAP System Manager o la CLI de ONTAP. Para ver todos los problemas, haga clic en Ver link:concept_fix_ontap_issues_directly_from_unified_manager.html["Solución de problemas de ONTAP directamente desde Unified Manager"] si quiere más información.



== Panel capacidad

Al ver todos los clústeres, este panel muestra la capacidad física utilizada (tras aplicar ahorros de eficiencia del almacenamiento) y la capacidad física disponible (sin incluir el potencial ahorro de eficiencia del almacenamiento) para cada clúster, el número de días que se prevé que los discos se llenen, La tasa de reducción de datos basada en la configuración de eficiencia del almacenamiento de ONTAP configurada. También incluye la capacidad utilizada para los niveles de cloud que haya configurado. Al hacer clic en el gráfico de barras irá la página del inventario de agregados para ese clúster. Al hacer clic en el texto "Days to Full" se muestra un mensaje que identifica el agregado con la menor cantidad de días de capacidad restantes; haga clic en el nombre del agregado para ver más detalles.

Al ver un único clúster, este panel muestra la capacidad física utilizada y la capacidad física disponible de los agregados de datos ordenados por cada tipo de disco individual del nivel local y del nivel de cloud. Al hacer clic en el gráfico de barras de un tipo de disco, se abre la página de inventario de volúmenes de los volúmenes que usan ese tipo de disco.



== Panel rendimiento capacidad

Cuando se visualizan todos los clústeres, este panel muestra el valor de capacidad de rendimiento de cada clúster (promediado en la 1 hora anterior) y el número de días hasta que la capacidad de rendimiento alcance el límite superior (según la tasa de crecimiento diaria). Al hacer clic en el gráfico de barras, irá la página del inventario de nodos de ese clúster. Tenga en cuenta que la página del inventario de nodos muestra la capacidad de rendimiento media de las 72 horas anteriores. Al hacer clic en el texto "Days to Full" se muestra un mensaje que identifica el nodo con la menor cantidad de días de capacidad de rendimiento restantes; haga clic en el nombre del nodo para ver más detalles.

Al ver un único clúster, este panel muestra los valores de porcentaje de capacidad de rendimiento del clúster utilizada, de IOPS totales y de rendimiento total (MB/s), así como el número de días que tardan en alcanzar el límite superior de cada una de estas tres métricas.



== Panel Workload IOPS

Al ver un solo clúster, este panel muestra el número total de cargas de trabajo que se están ejecutando actualmente en un determinado rango de IOPS e indica el número de cada tipo de disco cuando pasa el cursor por encima del gráfico.



== Panel Workload Performance

Este panel muestra el número total de cargas de trabajo conformes y no conformes que se asignan a cada política de nivel de servicio de rendimiento (PSL). También muestra la cantidad de cargas de trabajo a las que no se asigna una PSL. Al hacer clic en un gráfico de barras, se le llevan a las cargas de trabajo conformes asignadas a esa política en la página de cargas de trabajo. Al hacer clic en el número que sigue al gráfico de barras, se muestran las cargas de trabajo conformes y no conformes asignadas a esa política.



== Panel de seguridad

El panel Seguridad presenta el estado de seguridad de alto nivel para todos los clústeres o un único clúster, según la vista actual. Este panel muestra:

* una lista de los eventos de seguridad recibidos en las últimas 24 horas. Haga clic en un evento para ver los detalles en la página de detalles Event
* el estado de seguridad del clúster (recuento de clústeres compatibles y no compatibles)
* El estado de seguridad de los equipos virtuales de almacenamiento (recuento de equipos virtuales de almacenamiento que cumplen las normativas y no cumplen las normativas).
* el estado de cifrado de volúmenes (número de volúmenes cifrados o no cifrados).
* el estado del volumen antiransomware (recuento de volúmenes con antiransomware que están habilitados o deshabilitados).


Puede hacer clic en los gráficos de barras de los clústeres conformes a la normativa y no conformes a la normativa, VM de almacenamiento, volúmenes cifrados y estado del antivirus de volúmenes, para acceder a las páginas respectivas y ver los detalles de seguridad de los clústeres filtrados, las máquinas virtuales de almacenamiento y los volúmenes.

El cumplimiento se basa en la http://www.netapp.com/us/media/tr-4569.pdf["Guía de fortalecimiento de la seguridad de NetApp para ONTAP 9"]. Haga clic en la flecha derecha de la parte superior del panel para ver los detalles de seguridad de todos los clústeres de la página Seguridad. Para obtener más información, consultelink:../health-checker/task_view_detailed_security_status_for_clusters_and_svms.html["Visualización detallada del estado de seguridad para clústeres y máquinas virtuales de almacenamiento"].



== Panel Data Protection

Este panel muestra el resumen de protección de datos de uno o todos los clústeres de un centro de datos. Se muestra el número total de eventos de protección de datos, eventos de MetroCluster y el número de eventos activos generados en las últimas 24 horas en ONTAP. Al hacer clic en el enlace de cada uno de estos eventos, se abre la página de detalles Event. Puede hacer clic en el enlace *Ver todo* para ver todos los eventos de protección activos en la página de inventario de Event Management. El panel muestra:

* La cantidad de volúmenes en un clúster o todos los clústeres de un centro de datos protegido por copias de Snapshot.
* La cantidad de volúmenes en un clúster o todos los clústeres de un centro de datos protegido por relaciones de SnapMirror. Para las relaciones de SnapMirror, se considera el número de volúmenes en el clúster de origen.
* La cantidad de clústeres o todos los clústeres de un centro de datos protegido por la configuración de MetroCluster sobre IP o FC.
* El número de relaciones de volumen con el objetivo de punto de recuperación (RPO) de SnapMirror está desfase en función del estado de desfase.


Puede pasar el ratón sobre el mismo para ver los recuentos y leyendas correspondientes. Puede hacer clic en la flecha derecha de la parte superior del panel para ver los detalles de uno o todos los clústeres de la página Data Protection. También puede hacer clic en:

* Los gráficos de barras de volúmenes no protegidos y volúmenes protegidos por copias Snapshot para ir a la página Volumes y ver los detalles.
* Los gráficos de barras de los clústeres protegidos o no están protegidos por la configuración de MetroCluster para ir a la página Clusters y ver los detalles.
* Los gráficos de barras de todas las relaciones se van a la página Relaciones, donde se filtran los detalles en función del clúster de origen.


Para obtener más información, consulte link:../data-protection/view-protection-status.html["Ver el estado de protección de volumen"].



== Panel de descripción del uso

Al ver todos los clústeres, puede elegir ver clústeres ordenados por IOPS más alta, mayor rendimiento (MB/s) o mayor capacidad física utilizada.

Al ver un único clúster, puede elegir ver cargas de trabajo ordenadas por IOPS más alta, mayor rendimiento (MB/s) o mayor capacidad lógica utilizada.

*Información relacionada*

link:../events/task_fix_issues_using_um_automatic_remediations.html["Solución de problemas mediante soluciones automáticas de Unified Manager"]

link:../performance-checker/task_display_information_about_performance_event.html["Mostrar información acerca de los eventos de rendimiento"]

link:../performance-checker/concept_manage_performance_using_perf_capacity_available_iops.html["Gestión del rendimiento mediante la capacidad de rendimiento y la información de IOPS disponible"]

link:../health-checker/reference_health_volume_details_page.html["Página de detalles Volume / Health"]

link:../performance-checker/reference_performance_event_analysis_and_notification.html["Análisis y notificación de eventos de rendimiento"]

link:../events/reference_description_of_event_severity_types.html["Descripción de los tipos de gravedad de los eventos"]

link:../performance-checker/concept_sources_of_performance_events.html["Fuentes de eventos de rendimiento"]

link:../health-checker/concept_manage_cluster_security_objectives.html["Gestión de los objetivos de seguridad del clúster"]

link:../performance-checker/concept_monitor_cluster_performance_from_cluster_landing_page.html["Supervisar el rendimiento del clúster en la página Performance Cluster Landing"]

link:../performance-checker/concept_monitor_performance_using_object_performance.html["Supervisión del rendimiento mediante las páginas Performance Inventory"]
