---
permalink: storage-mgmt/task_monitor_metrocluster_replication.html 
sidebar: sidebar 
keywords: monitor, metrocluster, replication 
summary: Puede supervisar y diagnosticar la condición de estado general de las conexiones lógicas mientras hace mirroring de los datos. Es posible identificar los problemas o cualquier riesgo que interrumpa el mirroring de componentes del clúster, como agregados, nodos y máquinas virtuales de almacenamiento. 
---
= Supervisar la replicación de MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede supervisar y diagnosticar la condición de estado general de las conexiones lógicas mientras hace mirroring de los datos. Es posible identificar los problemas o cualquier riesgo que interrumpa el mirroring de componentes del clúster, como agregados, nodos y máquinas virtuales de almacenamiento.

Unified Manager utiliza alertas de estado del sistema para supervisar el estado de los componentes y la conectividad en la configuración de MetroCluster.

*Lo que necesitará*

Tanto el clúster local como el remoto de la configuración de MetroCluster se deben añadir a Unified Manager



== Visualización de la replicación para las configuraciones de MetroCluster over IP

En el caso de las configuraciones de MetroCluster over IP, el estado de replicación de datos se muestra en la vista de topología de un clúster protegido por MetroCluster mediante IP desde las siguientes vistas del panel de navegación izquierdo de Unified Manager:

* *Almacenamiento* > *Clusters* > *Protección: Vista MetroCluster*
* *Protección* > *Relaciones* > *relación: MetroCluster* vista


Para obtener más información, consulte link:../storage-mgmt/task_monitor_metrocluster_configurations.html#monitor-connectivity-issues-in-metrocluster-over-ip["Supervise los problemas de conectividad en MetroCluster por IP"].



== Visualización de la replicación para configuraciones de MetroCluster over FC

Siga estos pasos para determinar si hay problemas en la replicación de datos para la configuración de MetroCluster over FC.

.Pasos
. En el panel de navegación izquierdo, haga clic en *almacenamiento* > *clústeres*.
+
Se muestra una lista de los clústeres supervisados.

. En la vista *Estado: Todos los clústeres*, haga clic en el nombre del clúster para el que desea ver los detalles de la replicación de MetroCluster. En la página *Cluster / Health details*, haga clic en la ficha *MetroCluster Replication*.
+
La topología de la configuración de MetroCluster que se va a replicar se muestra en el sitio local en el área de objetos del clúster correspondiente con la información sobre el sitio remoto en el que se están reflejando los datos. Si mueve el puntero sobre el icono, puede ver información detallada sobre el evento generado.



Puede utilizar la información que se muestra en el para rectificar cualquier problema de replicación. Si detecta problemas de mirroring en la configuración de MetroCluster, debe iniciar sesión en System Manager o acceder a la CLI de ONTAP para resolver los problemas.

*Información relacionada*

link:../health-checker/reference_health_cluster_details_page.html["Página de detalles Cluster / Health"]
