---
permalink: health-checker/concept_configure_backup_for_windows.html 
sidebar: sidebar 
keywords: backup, restore, windows, netapp, snapshot copy, copies, configure, backup 
summary: Active IQ Unified Manager admite backup y restauración usando snapshots de NetApp en el sistema operativo Windows con la ayuda de LUN con el protocolo iSCSI. 
---
= Configuración de la copia de seguridad en Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager admite backup y restauración usando snapshots de NetApp en el sistema operativo Windows con la ayuda de LUN con el protocolo iSCSI.

Se puede realizar un backup basado en Snapshot mientras todos los servicios de Unified Manager están en ejecución. Como parte de la Snapshot, se captura un estado coherente de la base de datos a medida que el backup coloca un bloqueo de lectura global en toda la base de datos que evita las escrituras simultáneas. En el caso de que el sistema Unified Manager esté instalado en el sistema operativo Windows para realizar backups y restauraciones con Snapshot de NetApp, primero debe configurar Unified Manager backup en Snapshot mediante la consola de mantenimiento.

Antes de configurar Unified Manager para crear copias Snapshot, debe realizar las siguientes tareas de configuración.

* Configure el clúster ONTAP
* Configurar el equipo host de Windows

