---
permalink: health-checker/concept_common_unified_manager_administrative_workflows_and_tasks.html 
sidebar: sidebar 
keywords: Common, unified, manager, health, workflows, tasks 
summary: 'Algunos flujos de trabajo administrativos y tareas comunes asociados con Unified Manager incluyen la selección de los clústeres de almacenamiento que se van a supervisar; el diagnóstico de condiciones que afectan negativamente a la disponibilidad de los datos, la capacidad y la protección; la restauración de datos perdidos; la configuración y la gestión de volúmenes; y la agrupación y el envío de datos de diagnóstico al soporte técnico (cuando sea necesario).' 
---
= Flujos de trabajo y tareas comunes del estado de Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Algunos flujos de trabajo administrativos y tareas comunes asociados con Unified Manager incluyen la selección de los clústeres de almacenamiento que se van a supervisar; el diagnóstico de condiciones que afectan negativamente a la disponibilidad de los datos, la capacidad y la protección; la restauración de datos perdidos; la configuración y la gestión de volúmenes; y la agrupación y el envío de datos de diagnóstico al soporte técnico (cuando sea necesario).

Unified Manager permite a los administradores de almacenamiento ver una consola, evaluar la capacidad general, la disponibilidad y el estado de protección de los clústeres de almacenamiento gestionados y, a continuación, identificar, localizar, diagnosticar y asignar rápidamente para solucionar cualquier problema específico que pueda surgir.

Los problemas más importantes relacionados con un clúster, una máquina virtual de almacenamiento (SVM), un volumen o un volumen FlexGroup que afectan a la capacidad de almacenamiento o la disponibilidad de datos de los objetos de almacenamiento gestionados se muestran en los gráficos de estado del sistema y los eventos en la página Dashboard. Cuando se identifican problemas críticos, esta página proporciona enlaces para respaldar flujos de trabajo de solución de problemas adecuados.

Unified Manager también se puede incluir en los flujos de trabajo que incluyen herramientas de capacidad de gestión relacionadas, como OnCommand Workflow Automation (WFA), para dar soporte a la configuración directa de los recursos de almacenamiento.

En este documento se describen los flujos de trabajo comunes relacionados con las siguientes tareas administrativas:

* Diagnóstico y gestión de problemas de disponibilidad
+
Si los problemas de fallo de hardware o de configuración de recursos de almacenamiento ocasionan la visualización de eventos de disponibilidad de datos en la página Consola, los administradores de almacenamiento pueden seguir los enlaces integrados para ver información de conectividad sobre el recurso de almacenamiento afectado, ver consejos para la solución de problemas y asignar solución de problemas a otros administradores.

* Configurar y supervisar incidentes de rendimiento
+
El administrador puede supervisar y gestionar el rendimiento de los recursos del sistema de almacenamiento que se supervisan. Consulte link:../performance-checker/concept_introduction_to_unified_manager_performance_monitoring.html["Introducción a la supervisión del rendimiento de Active IQ Unified Manager"] si quiere más información.

* Diagnosticar y gestionar problemas de capacidad de volumen
+
Si los problemas de capacidad de almacenamiento de volumen se muestran en la página Consola, los administradores de almacenamiento pueden seguir los enlaces integrados para ver las tendencias actuales e históricas relacionadas con la capacidad de almacenamiento del volumen afectado, ver asesoramiento sobre solución de problemas y asignar solución de problemas a otros administradores.

* Configuración, supervisión y diagnóstico de problemas en las relaciones de protección
+
Después de crear y configurar relaciones de protección, los administradores de almacenamiento pueden ver los posibles problemas relacionados con las relaciones de protección, el estado actual de las relaciones de protección, la información de éxito actual e histórica de las relaciones afectadas y el asesoramiento sobre solución de problemas. Consulte link:../data-protection/concept_create_and_monitor_protection_relationships.html["Creación, supervisión y solución de problemas de relaciones de protección"] si quiere más información.

* Crear archivos de copia de seguridad y restaurar datos a partir de archivos de copia de seguridad.
* Asociación de objetos de almacenamiento con anotaciones
+
Al asociar los objetos de almacenamiento con anotaciones, los administradores de almacenamiento pueden filtrar y ver los eventos relacionados con los objetos de almacenamiento, lo que permite a los administradores de almacenamiento priorizar y resolver los problemas asociados con los eventos.

* El uso de API REST para ayudar a gestionar los clústeres mediante la visualización de la información de estado, capacidad y rendimiento que captura Unified Manager. Consulte link:../api-automation/concept_get_started_with_um_apis.html["Primeros pasos con API de REST de Active IQ Unified Manager"] si quiere más información.
* Enviar un bundle de soporte al soporte técnico
+
Los administradores de almacenamiento pueden recuperar y enviar un bundle de soporte al soporte técnico mediante la consola de mantenimiento. Los paquetes de soporte se deben enviar al soporte técnico cuando el problema requiera un diagnóstico y una solución de problemas más detallados de lo que proporcione un mensaje de AutoSupport.


