---
permalink: health-checker/reference_description_of_cluster_object_windows_and_dialog_boxes.html 
sidebar: sidebar 
keywords: description, cluster, object, windows, dialog boxes 
summary: Es posible ver todos los clústeres y los objetos del clúster desde la página de objetos de almacenamiento correspondiente. También puede ver los detalles desde la página de detalles del objeto de almacenamiento correspondiente. Ahora se puede iniciar la interfaz de usuario de System Manager desde las siguientes secciones de ALMACENAMIENTO Y PROTECCIÓN del INVENTARIO. 
---
= Descripción de las ventanas y cuadros de diálogo del objeto del clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible ver todos los clústeres y los objetos del clúster desde la página de objetos de almacenamiento correspondiente. También puede ver los detalles desde la página de detalles del objeto de almacenamiento correspondiente. Ahora se puede iniciar la interfaz de usuario de System Manager desde las siguientes secciones de ALMACENAMIENTO Y PROTECCIÓN del INVENTARIO.

* Páginas Cluster Inventory, Cluster Health y Cluster Performance
* Páginas Aggregate Inventory, Aggregate Health y Aggregate Performance
* Páginas Volume Inventory, Volume Health y Volume Performance
* Páginas Node Inventory and Node Performance
* Páginas de inventario de StorageVM, estado de StorageVM y rendimiento de StorageVM
* Páginas de relaciones de protección

