---
permalink: health-checker/task_add_values_to_annotations.html 
sidebar: sidebar 
keywords: add, values, annotations 
summary: Puede agregar valores a anotaciones y, a continuación, asociar objetos de almacenamiento a un par de nombre y valor de anotación concreto. Añadir valores a anotaciones le ayuda a gestionar los objetos de almacenamiento de forma más eficaz. 
---
= Adición de valores a anotaciones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede agregar valores a anotaciones y, a continuación, asociar objetos de almacenamiento a un par de nombre y valor de anotación concreto. Añadir valores a anotaciones le ayuda a gestionar los objetos de almacenamiento de forma más eficaz.

*Lo que necesitará*

Debe tener el rol de administrador de aplicaciones o de administrador del almacenamiento.

No se pueden agregar valores a anotaciones predefinidas.

.Pasos
. En el panel de navegación izquierdo, haga clic en *Administración de almacenamiento* > *Anotaciones*.
. En la página *Anotaciones*, seleccione la anotación a la que desea agregar un valor y, a continuación, haga clic en *Agregar* en la sección *valores*.
. En el cuadro de diálogo *Agregar valor de anotación*, especifique un valor para la anotación.
+
El valor especificado debe ser único para la anotación seleccionada.

. Haga clic en *Agregar*.

