---
permalink: health-checker/task_edit_individual_volume_health_threshold_settings.html 
sidebar: sidebar 
keywords: edit, individual, volume, health, threshold, settings 
summary: Es posible editar la configuración del umbral de estado para la capacidad de volumen, el crecimiento, la cuota y la reserva de espacio de uno o más volúmenes. Cuando se supera un umbral, se generan alertas y se reciben notificaciones. Estas notificaciones le ayudan a tomar medidas preventivas basadas en el evento generado. 
---
= Editar la configuración de umbral de estado de cada volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible editar la configuración del umbral de estado para la capacidad de volumen, el crecimiento, la cuota y la reserva de espacio de uno o más volúmenes. Cuando se supera un umbral, se generan alertas y se reciben notificaciones. Estas notificaciones le ayudan a tomar medidas preventivas basadas en el evento generado.

*Lo que necesitará*

Debe tener el rol de administrador de aplicaciones o de administrador del almacenamiento.

Basándose en los cambios de los valores de umbral, los eventos se generan o se vuelven obsoletos en el siguiente ciclo de supervisión.

Tenga en cuenta que cuando se habilita la opción Autofila en un volumen, se consideran límites de capacidad según el tamaño máximo de volumen establecido por crecimiento automático, no según el tamaño del volumen original.

[NOTE]
====
El valor predeterminado de 1000 copias de Snapshot se aplica solo a los volúmenes FlexVol cuando la versión de ONTAP es 9.4 o posterior, y a los volúmenes FlexGroup cuando la versión de ONTAP es 9.8 y posterior. En los clústeres instalados con versiones anteriores del software ONTAP, el número máximo es de 250 copias snapshot por volumen. En estas versiones anteriores, Unified Manager interpreta este número 1000 (y cualquier número entre 1000 y 250) como 250; lo que significa que continuará recibiendo eventos cuando el número de copias Snapshot llegue a 250. Si desea establecer este umbral en menos de 250 para estas versiones anteriores, debe establecer el umbral en 250 o inferior aquí, en la vista Estado: Todos los volúmenes o en la página de detalles volumen / Estado.

====
.Pasos
. En el panel de navegación izquierdo, haga clic en *almacenamiento* > *volúmenes*.
. En la vista *Estado: Todos los volúmenes*, seleccione uno o más volúmenes y, a continuación, haga clic en *Editar umbrales*.
. En el cuadro de diálogo *Editar umbrales de volumen*, edite la configuración de umbral de una de las siguientes opciones: Capacidad, copias Snapshot, cuota de qtree, crecimiento o inodos. Para ello, active la casilla de verificación correspondiente y, a continuación, modifique la configuración.
. Haga clic en *Guardar*.


*Información relacionada*

link:../config/task_add_users.html["Adición de usuarios"]
