---
permalink: health-checker/task_perform_diagnotstic_actions_for_volume_offline_conditions.html 
sidebar: sidebar 
keywords: perform, diagnostic actions, volume, offline, conditions 
summary: Después de navegar a la página de detalles Volume/Health de un volumen al que se informa que está sin conexión, puede buscar información adicional útil para diagnosticar la condición de volumen sin conexión. 
---
= Realización de acciones de diagnóstico para condiciones de sin conexión de un volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de navegar a la página de detalles Volume/Health de un volumen al que se informa que está sin conexión, puede buscar información adicional útil para diagnosticar la condición de volumen sin conexión.

*Lo que necesitará*

Debe tener el rol de operador, administrador de aplicaciones o administrador de almacenamiento.

Si el volumen que se informa sin conexión no se desconecta deliberadamente, ese volumen puede estar sin conexión por varios motivos.

A partir de la página de detalles Volume / Health del volumen sin conexión, puede ir a otras páginas y paneles para confirmar o eliminar las posibles causas:

* Haga clic en *volumen / Página de detalles Health* para determinar si el volumen está desconectado debido a que su nodo host está inactivo y la conmutación por error de almacenamiento a su par ha asociado también ha fallado.
+
Consulte link:task_determine_if_volume_offline_condition_is_by_down_cluster_node.html["Determinar si una condición de volumen sin conexión es causada por un nodo inactivo"].

* Haga clic en *volumen / Estado* página de detalles vínculos para determinar si el volumen está sin conexión y su máquina virtual de almacenamiento host (SVM) se detiene porque el nodo que aloja el volumen raíz de esa SVM está inactivo.
+
Consulte link:task_determine_if_volume_is_offline_and_its_svm_is_stopped.html["Determinar si un volumen está sin conexión y la SVM se ha detenido debido a que el nodo está inactivo"].

* Haga clic en *volumen / Página de detalles Health* para determinar si el volumen está fuera de línea debido a discos rotos en su agregado de host.
+
Consulte link:task_determine_if_volume_is_offline_because_of_broken_disks.html["Determinar si un volumen está sin conexión debido a discos dañados en un agregado"].



*Información relacionada*

link:../config/reference_unified_manager_roles_and_capabilities.html["Roles y funcionalidades de usuario de Unified Manager"]
