---
permalink: health-checker/task_add_alerts_for_security_events.html 
sidebar: sidebar 
keywords: add, alerts, security events 
summary: Es posible configurar alertas para eventos de seguridad individuales, como cualquier otro evento recibido por Unified Manager. Además, si desea tratar todos los eventos de seguridad por igual y enviar correo electrónico a la misma persona, puede crear una única alerta para notificarle cuando se desencadenen eventos de seguridad. 
---
= Agregar alertas para eventos de seguridad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible configurar alertas para eventos de seguridad individuales, como cualquier otro evento recibido por Unified Manager. Además, si desea tratar todos los eventos de seguridad por igual y enviar correo electrónico a la misma persona, puede crear una única alerta para notificarle cuando se desencadenen eventos de seguridad.

*Lo que necesitará*

Debe tener el rol de administrador de aplicaciones o de administrador del almacenamiento.

En el siguiente ejemplo se muestra cómo crear una alerta para el evento de seguridad "'Protocolo Telnet habilitado'". Esto enviará una alerta si el acceso Telnet está configurado para el acceso administrativo remoto al clúster. Puede utilizar esta misma metodología para crear alertas para todos los eventos de seguridad.

.Pasos
. En el panel de navegación izquierdo, haga clic en *Administración de almacenamiento* > *Configuración de alertas*.
. En la página *Configuración de alertas*, haga clic en *Agregar*.
. En el cuadro de diálogo *Agregar alerta*, haga clic en *Nombre* e introduzca un nombre y una descripción para la alerta.
. Haga clic en *Recursos* y seleccione el clúster o clúster en el que desea activar esta alerta.
. Haga clic en *Eventos* y realice las siguientes acciones:
+
.. En la lista gravedad del evento, seleccione *Advertencia*.
.. En la lista Eventos coincidentes, seleccione *Protocolo Telnet activado*.


. Haga clic en *acciones* y, a continuación, seleccione el nombre del usuario que recibirá el correo electrónico de alerta en el campo *Alerta a estos usuarios*.
. Configure cualquier otra opción de esta página para la frecuencia de notificación, la emisión de toques SNMP y la ejecución de un script.
. Haga clic en *Guardar*.

