---
permalink: health-checker/task_create_volume_where_backups_are_stored.html 
sidebar: sidebar 
keywords: configure, snapshot copy, copies location 
summary: Puede configurar el volumen donde se almacenarán las copias Snapshot en uno de los clústeres de ONTAP mediante System Manager de ONTAP o mediante la interfaz de línea de comandos de ONTAP. 
---
= Configurar la ubicación de la copia Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar el volumen donde se almacenarán las copias Snapshot en uno de los clústeres de ONTAP mediante System Manager de ONTAP o mediante la interfaz de línea de comandos de ONTAP.

*Lo que necesitará*

El clúster, la máquina virtual de almacenamiento y el volumen deben cumplir los siguientes requisitos:

* Requisitos del clúster:
+
** Se debe instalar ONTAP 9.3 o superior
** Debe estar geográficamente cerca del servidor de Unified Manager
** Unified Manager se puede supervisar, pero no es obligatorio


* Requisitos de Storage VM:
+
** El modificador de nombre y la asignación de nombres deben configurarse para que utilicen "'files'".
** Los usuarios locales creados para corresponder con los usuarios del cliente
** Asegúrese de que está seleccionado todo el acceso de lectura/escritura
** Asegúrese de que Superuser Access esté definido en «'any'» en la política de exportación
** NFS para Snapshot de NetApp para Linux
** NFSv4 deben estar habilitados en el servidor NFS y el dominio de ID de NFSv4 especificado en las máquinas virtuales de almacenamiento y cliente
** El volumen debe ser al menos el doble del tamaño del directorio Unified Manager/opt/netapp/data
+
Utilice el comando du -sh /opt/netapp/data/ para comprobar el tamaño actual.



* Requisitos del volumen:
+
** El volumen debe tener al menos el doble de tamaño del directorio Unified Manager /opt/netapp/data
** El estilo de seguridad se debe establecer en UNIX
** Debe deshabilitarse la política de Snapshot local
** Se debe habilitar autosize para el volumen
** El nivel de servicio de rendimiento debe definirse en una política con una tasa elevada de IOPS y una baja latencia, como «'Extreme»




Para obtener los pasos detallados para crear el volumen NFS, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_NFSv4_in_Cluster-Mode["Cómo configurar NFSv4 en ONTAP 9"] y la http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-nfsv3-cg/home.html["Guía exprés de configuración de NFS de ONTAP 9"].
