---
permalink: health-checker/task_delete_snapshot_copies.html 
sidebar: sidebar 
keywords: delete, snapshot copies 
summary: Puede eliminar una copia Snapshot para conservar espacio o a liberar espacio en disco, o bien puede eliminar la copia Snapshot si ya no se necesita. 
---
= Eliminar copias Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede eliminar una copia Snapshot para conservar espacio o a liberar espacio en disco, o bien puede eliminar la copia Snapshot si ya no se necesita.

*Lo que necesitará*

Debe tener el rol de administrador de aplicaciones o de administrador del almacenamiento.

El volumen debe estar en línea.

Para eliminar una copia snapshot que está ocupada o bloqueada, debe haber liberado la copia snapshot de la aplicación que la estaba utilizando.

* No puede eliminar la copia snapshot básica de un volumen principal si un volumen FlexClone está utilizando esa copia snapshot.
+
La copia Snapshot básica es la copia Snapshot que se utiliza para crear el volumen FlexClone y muestra el estado `Busy` Y Dependencia de aplicaciones como `Busy, Vclone` en el volumen principal.

* No se puede eliminar una copia snapshot bloqueada que se haya utilizado en una relación de SnapMirror.
+
La copia snapshot está bloqueada y es necesaria para la siguiente actualización.



.Pasos
. En el panel de navegación izquierdo, haga clic en *almacenamiento* > *volúmenes*.
. En la vista *Estado: Todos los volúmenes*, seleccione el volumen que contiene las copias Snapshot que desea ver.
+
Se muestra la lista de copias Snapshot.

. En la página de detalles *Volume / Health*, haga clic en la ficha *Capacity*.
. En el panel *Detalles* de la ficha *capacidad*, en la sección otros detalles, haga clic en el enlace que se encuentra junto a *copias Snapshot*.
+
El número de copias de Snapshot es un enlace que muestra la lista de copias de Snapshot.

. En la vista *copias Snapshot*, seleccione las copias Snapshot que desee eliminar y, a continuación, haga clic en *Eliminar seleccionadas*.

