---
permalink: health-checker/task_delete_groups.html 
sidebar: sidebar 
keywords: delete, groups 
summary: Un grupo se puede eliminar de Unified Manager cuando ya no se necesita el grupo. 
---
= Eliminación de grupos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un grupo se puede eliminar de Unified Manager cuando ya no se necesita el grupo.

*Lo que necesitará*

* Ninguno de los objetos de almacenamiento (clústeres, SVM o volúmenes) debe estar asociado con cualquier regla de grupo asociada con el grupo que desea eliminar.
* Debe tener el rol de administrador de aplicaciones o de administrador del almacenamiento.


.Pasos
. En el panel de navegación izquierdo, haga clic en *Administración de almacenamiento* > *grupos*.
. En la ficha *grupos*, seleccione el grupo que desea eliminar y, a continuación, haga clic en *Eliminar*.
. En el cuadro de diálogo *Advertencia*, confirme la eliminación haciendo clic en *Sí*.
+
Al eliminar un grupo no se eliminan las acciones de grupo asociadas al grupo. Sin embargo, estas acciones de grupo se desasignarán una vez eliminado el grupo.


