---
permalink: health-checker/task_view_node_list_and_details.html 
sidebar: sidebar 
keywords: view, node list, details 
summary: 'Puede usar la vista Health: All Nodes para ver la lista de nodos en los clústeres. Puede usar la página de detalles Cluster / Health para ver información detallada acerca de los nodos que forman parte del clúster que se supervisa.' 
---
= Ver la lista y los detalles del nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar la vista Health: All Nodes para ver la lista de nodos en los clústeres. Puede usar la página de detalles Cluster / Health para ver información detallada acerca de los nodos que forman parte del clúster que se supervisa.

*Lo que necesitará*

Debe tener el rol de operador, administrador de aplicaciones o administrador de almacenamiento.

Es posible ver detalles como el estado del nodo, el clúster que contiene el nodo, detalles de capacidad del agregado (usado y total) y detalles de capacidad bruta (utilizable, de reserva y total). También puede obtener información acerca de las parejas de alta disponibilidad, bandejas de discos y puertos.

.Pasos
. En el panel de navegación izquierdo, haga clic en *almacenamiento* > *nodos*.
. En la vista *Estado: Todos los nodos*, haga clic en el nodo cuyos detalles desee ver.
+
La información detallada del nodo seleccionado se muestra en la página de detalles Cluster / Health. En el panel izquierdo se muestra la lista de pares de alta disponibilidad. De forma predeterminada, ha Details está abierto, lo que muestra detalles de estado de alta disponibilidad y eventos relacionados con el par de alta disponibilidad seleccionado.

. Para ver otros detalles sobre el nodo, realice la acción correspondiente:
+
[cols="2*"]
|===
| Para ver... | Haga clic en... 


 a| 
Detalles acerca de las bandejas de discos
 a| 
*Bandejas de discos*.



 a| 
Información relacionada con el puerto
 a| 
*Puertos*.

|===


Para obtener más información, consulte:

* link:../performance-checker/performance-view-all.html#performance-all-nodes-view["Rendimiento: Vista de todos los nodos"]
* link:../performance-checker/concept_view_node_and_aggregate_available_iops_values.html["Ver los valores de IOPS disponibles de los nodos y los agregados"]
* link:../performance-checker/concept_view_node_and_aggregate_performance_capacity_used_values.html["Ver los valores de capacidad de rendimiento de los nodos y los agregados"]

