---
permalink: install-vapp/task_upgrade_unified_manager_vapp.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: Puede actualizar a Unified Manager en VMware vSphere 
---
= Actualizar Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede actualizar Active IQ Unified Manager a la versión 9.12 únicamente de la versión 9.10 o la 9.11.

Durante el proceso de actualización, Unified Manager no está disponible. Debe completar todas las operaciones en ejecución antes de actualizar Unified Manager.

Si Unified Manager se empareja con una instancia de OnCommand Workflow Automation y hay nuevas versiones del software disponibles para ambos productos, debe desconectar los productos y, a continuación, configurar una nueva conexión de Workflow Automation tras las actualizaciones. Si solo actualiza uno de los productos, deberá iniciar sesión en Workflow Automation tras la actualización y comprobar que aún se recopilen datos de Unified Manager.

.Pasos
. Siga los pasos de link:task_download_unified_manager_iso_image_vapp.html["Descargue la imagen ISO de Unified Manager"].
. Además, siga los pasos descritos en link:task_upgrade_unified_manager_virtual_appliance_vapp.html["Actualice Unified Manager"].

