---
permalink: install-vapp/task_restart_unified_manager_virtual_machine.html 
sidebar: sidebar 
keywords: restart, unified manager, virtual, machine 
summary: 'Puede reiniciar la máquina virtual (VM) de Unified Manager desde la consola de mantenimiento. Debe reiniciar la máquina virtual después de generar un nuevo certificado de seguridad, o si hay un problema con la máquina virtual.' 
---
= Reiniciar la máquina virtual de Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede reiniciar la máquina virtual (VM) de Unified Manager desde la consola de mantenimiento. Debe reiniciar la máquina virtual después de generar un nuevo certificado de seguridad, o si hay un problema con la máquina virtual.

*Lo que necesitará*

* El dispositivo virtual debe estar encendido.
* Debe iniciar sesión en la consola de mantenimiento de Unified Manager como usuario de mantenimiento.


También puede reiniciar la máquina virtual desde vSphere mediante la opción VMware *Restart Guest*.

.Pasos
. En la consola de mantenimiento, seleccione *Configuración del sistema* > *Reiniciar máquina virtual*.
. Inicie la interfaz de usuario web de Unified Manager desde el explorador e inicie sesión.


*Información relacionada*

https://["Referencia de cmdlets de VMware vSphere PowerCLI: Restart-VMGuest"]
