---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: Puede restablecer la contraseña de JBoss específica de la instancia que se haya establecido durante la instalación. Es posible restablecer la contraseña de manera opcional; en caso de que el sitio requiera esta funcionalidad de seguridad para anular la configuración de instalación de Unified Manager. Esta operación también cambia la contraseña que JBoss utiliza para acceder a MySQL. 
---
= Cambio de la contraseña de JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede restablecer la contraseña de JBoss específica de la instancia que se haya establecido durante la instalación. Es posible restablecer la contraseña de manera opcional; en caso de que el sitio requiera esta funcionalidad de seguridad para anular la configuración de instalación de Unified Manager. Esta operación también cambia la contraseña que JBoss utiliza para acceder a MySQL.

*Lo que necesitará*

* Debe tener privilegios de administrador de Windows en el sistema en el que está instalado Unified Manager.
* Debe tener la contraseña del usuario raíz de MySQL.
* Debe poder acceder a todo lo que proporciona NetApp `password.bat` script en el directorio
+
`C:\Program Files\NetApp\essentials\bin`.



.Pasos
. Inicie sesión como usuario administrador en la máquina host de Unified Manager.
. Utilice la consola de servicios de Windows para detener los siguientes servicios de Unified Manager:
+
** Servicio de adquisición de NetApp Active IQ (OCIE-au)
** Servicio de servidores de gestión de Active IQ de NetApp (Oncommandsvc)


. Inicie el `password.bat` secuencia de comandos para iniciar el proceso de cambio de contraseña:
+
`C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`

. Cuando se le solicite, introduzca la contraseña de usuario raíz de MySQL.
. Cuando se le solicite, introduzca la nueva contraseña de usuario de JBoss y, a continuación, vuelva a introducirla para confirmarla.
+
Tenga en cuenta que la contraseña debe tener entre 8 y 16 caracteres, y debe contener al menos un dígito, mayúsculas y minúsculas caracteres, y al menos uno de estos caracteres especiales:

+
`+!@%^*-_+=[]:<>.?/~+`

. Una vez finalizado el script, inicie los servicios de Unified Manager mediante la consola de Windows Services:
+
** Servicio de servidores de gestión de Active IQ de NetApp (Oncommandsvc)
** Servicio de adquisición de NetApp Active IQ (OCIE-au)


. Después de iniciar todos los servicios, puede iniciar sesión en la interfaz de usuario de Unified Manager.

