---
permalink: config/concept_maintenance_console_menu.html 
sidebar: sidebar 
keywords: maintenance, console, menus 
summary: La consola de mantenimiento consta de distintos menús que permiten mantener y gestionar funciones especiales y ajustes de configuración del servidor de Unified Manager. 
---
= Menús de la consola de mantenimiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La consola de mantenimiento consta de distintos menús que permiten mantener y gestionar funciones especiales y ajustes de configuración del servidor de Unified Manager.

Según el sistema operativo en el que instaló Unified Manager, la consola de mantenimiento consta de los siguientes menús:

* Actualización de Unified Manager (solo VMware)
* Configuración de red (solo VMware)
* Configuración del sistema (sólo VMware)
+
.. Soporte/Diagnóstico
.. Restablecer certificado de servidor
.. Proveedor de datos externos
.. Restaurar copia de seguridad
.. Configuración del intervalo de sondeo de rendimiento
.. Deshabilite la autenticación SAML
.. Ver/cambiar puertos de aplicación
.. Depurar configuración de registro
.. Controlar el acceso al puerto MySQL 3306
.. Salga




Puede seleccionar el número de la lista para acceder a la opción de menú específica. Por ejemplo, para copia de seguridad y restauración, seleccione _4_.
