---
permalink: config/concept_what_role_based_access_control_does.html 
sidebar: sidebar 
keywords: role-based, access, control 
summary: El control de acceso basado en roles permite a los administradores gestionar grupos de usuarios definiendo roles. Si necesita restringir el acceso a funciones específicas para administradores seleccionados, debe configurar cuentas de administrador para ellos. Si desea restringir la información que los administradores pueden ver y las operaciones que pueden realizar, debe aplicar roles a las cuentas de administrador que cree. 
---
= Infórmate sobre el control de acceso basado en roles en Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El RBAC (control de acceso basado en roles) permite controlar quién tiene acceso a las distintas funciones y recursos del servidor Active IQ Unified Manager. El RBAC permite a los administradores gestionar grupos de usuarios mediante la definición de roles. Si necesitas restringir el acceso a determinadas funciones a administradores concretos, debes configurar cuentas de administrador para ellos. Si quieres restringir la información que los administradores pueden ver y las operaciones que pueden realizar, debes asignar roles a las cuentas de administrador que crees.

El servidor de gestión utiliza RBAC para los permisos de inicio de sesión de usuario y roles. Si no ha cambiado la configuración predeterminada del servidor de administración para el acceso de usuarios administrativos, no es necesario iniciar sesión para verlos.

Al iniciar una operación que requiere privilegios específicos, el servidor de administración le solicita que inicie sesión. Por ejemplo, para crear cuentas de administrador, debe iniciar sesión con acceso a la cuenta de Administrador de aplicaciones.
