---
permalink: config/task_test_configuration_of_authentication_servers_um_6_0.html 
sidebar: sidebar 
keywords: test, configuration, authentication servers 
summary: Puede validar la configuración de los servidores de autenticación para garantizar que el servidor de gestión pueda comunicarse con ellos. Puede validar la configuración buscando un usuario remoto o un grupo remoto desde los servidores de autenticación y autentificándolos con la configuración configurada. 
---
= Prueba de la configuración de los servidores de autenticación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede validar la configuración de los servidores de autenticación para garantizar que el servidor de gestión pueda comunicarse con ellos. Puede validar la configuración buscando un usuario remoto o un grupo remoto desde los servidores de autenticación y autentificándolos con la configuración configurada.

*Lo que necesitará*

* Usted debe haber habilitado la autenticación remota y configurado el servicio de autenticación para que el servidor de Unified Manager pueda autenticar el usuario remoto o el grupo remoto.
* Debe haber agregado los servidores de autenticación para que el servidor de administración pueda buscar el usuario remoto o el grupo remoto desde estos servidores y autentificarlos.
* Debe tener la función Administrador de aplicaciones.


Si el servicio de autenticación está establecido en Active Directory y si está validando la autenticación de usuarios remotos que pertenecen al grupo principal del servidor de autenticación, la información sobre el grupo principal no se muestra en los resultados de la autenticación.

.Pasos
. En el panel de navegación izquierdo, haga clic en *General* > *autenticación remota*.
. Haga clic en *probar autenticación*.
. En el cuadro de diálogo probar usuario, especifique el nombre de usuario y la contraseña del usuario remoto o el nombre de usuario del grupo remoto y, a continuación, haga clic en *Prueba*.
+
Si va a autenticar un grupo remoto, no debe introducir la contraseña.


