---
permalink: config/task_add_clusters.html 
sidebar: sidebar 
keywords: add cluster 
summary: Puede añadir un clúster a la Active IQ Unified Manager para poder supervisar el clúster. Esto incluye la capacidad de obtener información del clúster, como el estado, la capacidad, el rendimiento y la configuración del clúster, para poder encontrar y resolver cualquier problema que pueda ocurrir. 
---
= Añadir clústeres
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede añadir un clúster a la Active IQ Unified Manager para poder supervisar el clúster. Esto incluye la capacidad de obtener información del clúster, como el estado, la capacidad, el rendimiento y la configuración del clúster, para poder encontrar y resolver cualquier problema que pueda ocurrir.

*Lo que necesitará*

* Debe tener el rol de administrador de aplicaciones o de administrador del almacenamiento.
* Debe tener la siguiente información:
+
** Unified Manager admite clústeres de ONTAP en las instalaciones, ONTAP Select, Cloud Volumes ONTAP.
** El nombre de host o la dirección IP de administración del clúster
+
El nombre de host es el nombre FQDN o el nombre corto que Unified Manager utiliza para conectarse con el clúster. El nombre de host debe resolver a la dirección IP de administración del clúster.

+
La dirección IP de administración del clúster debe ser el LIF de gestión del clúster de la máquina virtual de almacenamiento (SVM) administrativa. Si utiliza un LIF de gestión de nodos, la operación da error.

** El clúster de debe ejecutar el software ONTAP versión 9.1 o posterior.
** Nombre de usuario y contraseña del administrador de ONTAP
+
Esta cuenta debe tener el rol _admin_ con acceso a aplicaciones establecido en _ontapi_, _Console_ y _http_.

** El número de puerto para conectarse al clúster mediante el protocolo HTTPS (por lo general, puerto 443)
** Tiene los certificados necesarios:
+
*Certificado SSL (HTTPS)*: Este certificado es propiedad de Unified Manager. Se genera un certificado SSL (HTTPS) autofirmado predeterminado con una instalación nueva de Unified Manager. NetApp recomienda actualizarlo a certificado firmado por CA para mejorar la seguridad. Si el certificado de servidor caduca, debe volver a regenerarlo y reiniciar Unified Manager para que los servicios incorporen el nuevo certificado. Para obtener más información acerca de la regeneración del certificado SSL, consulte link:../config/task_generate_an_https_security_certificate_ocf.html["Generar un certificado de seguridad HTTPS"].

+
*Certificado EMS*: Este certificado es propiedad de Unified Manager. Se usa durante la autenticación de notificaciones EMS que se reciben de ONTAP.

+
*Certificados para la comunicación mutua con TLS*: Se utiliza durante la comunicación mutua con TLS entre Unified Manager y ONTAP. La autenticación basada en certificados está habilitada para un clúster de acuerdo con la versión de ONTAP. Si el clúster que ejecuta la versión de ONTAP es inferior a la versión 9.5, la autenticación basada en certificados no está habilitada.

+
La autenticación basada en certificado no se habilita automáticamente para un clúster, si va a actualizar una versión anterior de Unified Manager. Sin embargo, puede habilitarla mediante la modificación y el guardado de los detalles del clúster. Si el certificado caduca, debe regenerarlo para incorporar el nuevo certificado. Para obtener más información sobre la visualización y regeneración del certificado, consulte link:../storage-mgmt/task_edit_clusters.html["Editar clústeres"].

+
[NOTE]
====
*** Puede añadir un clúster desde la interfaz de usuario web y la autenticación basada en certificado se habilita automáticamente.
*** Puede añadir un clúster mediante la CLI de Unified Manager, la autenticación basada en certificado no está habilitada de forma predeterminada. Si se añade un clúster mediante la CLI de Unified Manager, se deberá editar el clúster mediante la interfaz de usuario de Unified Manager. Puede ver link:https://docs.netapp.com/us-en/active-iq-unified-manager/events/reference_supported_unified_manager_cli_commands.html["Comandos de CLI de Unified Manager compatibles"] Para añadir un clúster mediante la interfaz de línea de comandos de Unified Manager.
*** Si la autenticación basada en certificados está habilitada para un clúster, y realiza el backup de Unified Manager desde un servidor y la restauración a otro servidor de Unified Manager donde se cambia el nombre de host o la dirección IP, la supervisión del clúster puede fallar. Para evitar el error, edite y guarde los detalles del clúster. Para obtener más información sobre cómo editar detalles del clúster, consulte link:../storage-mgmt/task_edit_clusters.html["Editar clústeres"].


====
+
*Certificados de clúster*: Este certificado es propiedad de ONTAP. No es posible añadir un clúster a Unified Manager con un certificado caducado y si el certificado ya ha caducado, debe volver a generarlo antes de añadir el clúster. Para obtener información acerca de la generación de certificados, consulte el artículo de la base de conocimientos (KB) https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_renew_an_SSL_certificate_in_ONTAP_9["Cómo renovar un certificado autofirmado de ONTAP en la interfaz de usuario de System Manager"^].



* Debe tener espacio suficiente en el servidor de Unified Manager. Se le impide agregar un clúster al servidor cuando ya se consume más del 90% del espacio en el directorio de la base de datos.


Para una configuración de MetroCluster, debe añadir los clústeres local y remoto, y los clústeres deben configurarse correctamente.

.Pasos
. En el panel de navegación izquierdo, haga clic en *Storage Management* > *Cluster Setup*.
. En la página Cluster Setup, haga clic en *Add*.
. En el cuadro de diálogo Add Cluster, especifique los valores requeridos, como el nombre de host o la dirección IP del clúster, el nombre de usuario, la contraseña y el número de puerto.
+
Es posible cambiar la dirección IP de gestión del clúster de IPv6 a IPv4 o de IPv4 a IPv6. La nueva dirección IP se refleja en la cuadrícula del clúster y en la página de configuración del clúster una vez completado el siguiente ciclo de supervisión.

. Haga clic en *Enviar*.
. En el cuadro de diálogo autorizar host, haga clic en *Ver certificado* para ver la información del certificado sobre el clúster.
. Haga clic en *Sí*.
+
Después de guardar los detalles del clúster, puede ver el certificado para la comunicación TLS mutua para un clúster.

+
Si la autenticación basada en certificados no está habilitada, Unified Manager comprueba el certificado solo cuando se añade el clúster inicialmente. Unified Manager no comprueba el certificado para cada llamada API a ONTAP.



Después de detectar todos los objetos de un clúster nuevo, Unified Manager comienza a recopilar datos históricos de rendimiento de los 15 días anteriores. Estas estadísticas se recopilan mediante la funcionalidad de recogida de continuidad de datos. Esta función le proporciona más de dos semanas de información sobre el rendimiento de un clúster inmediatamente después de añadir. Una vez completado el ciclo de recogida de continuidad de datos, se recogen datos de rendimiento del clúster en tiempo real, de forma predeterminada, cada cinco minutos.

[NOTE]
====
Dado que la recogida de 15 días de datos de rendimiento requiere un uso intensivo de la CPU, se sugiere escalonar la adición de nuevos clústeres de manera que las encuestas de recogida de continuidad de datos no se ejecuten en demasiados clústeres al mismo tiempo. Además, si reinicia Unified Manager durante el período de recogida de continuidad de datos, la recogida se detiene y verá vacíos en los gráficos de rendimiento correspondientes al periodo que falta.

====
[TIP]
====
Si recibe un mensaje de error que no puede añadir el clúster, compruebe si los relojes de los dos sistemas no están sincronizados y la fecha de inicio del certificado HTTPS de Unified Manager es posterior a la fecha del clúster. Debe asegurarse de que los relojes se sincronicen con NTP o un servicio similar.

====
*Información relacionada*

link:../config/task_install_ca_signed_and_returned_https_certificate.html#example-certificate-chain["Instalar una CA firmada y devolvió un certificado HTTPS"]
