---
permalink: config/task_disable_nested_groups_from_remote_authentication.html 
sidebar: sidebar 
keywords: disable, nested groups, remote, authentication 
summary: Si tiene habilitada la autenticación remota, puede deshabilitar la autenticación de grupos anidados para que solo los usuarios individuales y no los miembros de grupos se puedan autenticar de forma remota a Unified Manager. Puede deshabilitar los grupos anidados cuando desee mejorar el tiempo de respuesta de autenticación de Active Directory. 
---
= Deshabilitar grupos anidados de la autenticación remota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si tiene habilitada la autenticación remota, puede deshabilitar la autenticación de grupos anidados para que solo los usuarios individuales y no los miembros de grupos se puedan autenticar de forma remota a Unified Manager. Puede deshabilitar los grupos anidados cuando desee mejorar el tiempo de respuesta de autenticación de Active Directory.

*Lo que necesitará*

* Debe tener la función Administrador de aplicaciones.
* La desactivación de grupos anidados sólo se aplica cuando se utiliza Active Directory.


Al deshabilitar la compatibilidad con los grupos anidados en Unified Manager, es posible que se reduzca el tiempo de autenticación. Si la compatibilidad de grupos anidados está deshabilitada y, si se añade un grupo remoto a Unified Manager, los usuarios individuales deben ser miembros del grupo remoto para autenticarse en Unified Manager.

.Pasos
. En el panel de navegación izquierdo, haga clic en *General* > *autenticación remota*.
. Active la casilla de verificación *Desactivar búsqueda de grupo anidada*.
. Haga clic en *Guardar*.

