---
permalink: config/task_change_local_user_password.html 
sidebar: sidebar 
keywords: change, local, user, password 
summary: Es posible cambiar la contraseña de inicio de sesión de usuario local para evitar riesgos potenciales para la seguridad. 
---
= Cambiando la contraseña de usuario local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible cambiar la contraseña de inicio de sesión de usuario local para evitar riesgos potenciales para la seguridad.

*Lo que necesitará*

Debe iniciar sesión como usuario local.

Las contraseñas del usuario de mantenimiento y de los usuarios remotos no se pueden cambiar mediante estos pasos. Para cambiar una contraseña de usuario remoto, póngase en contacto con el administrador de contraseñas. Para cambiar la contraseña de usuario de mantenimiento, consulte link:task_use_maintenance_console.html["Mediante la consola de mantenimiento"].

.Pasos
. Inicie sesión en Unified Manager.
. En la barra de menús superior, haga clic en el icono de usuario y, a continuación, haga clic en *Cambiar contraseña*.
+
La opción *Cambiar contraseña* no se muestra si es un usuario remoto.

. En el cuadro de diálogo Change Password, introduzca la contraseña actual y la contraseña nueva.
. Haga clic en *Guardar*.


Si Unified Manager se configura en una configuración de alta disponibilidad, debe cambiar la contraseña en el segundo nodo de la configuración. Ambas instancias deben tener la misma contraseña.
