---
permalink: config/task_download_an_https_certificate_sign_request_ocf.html 
sidebar: sidebar 
keywords: download, https, certificate, signing, request 
summary: 'Puede descargar una solicitud de firma de certificación para el certificado de seguridad HTTPS actual para poder proporcionar el archivo a una entidad de certificación para firmar. Un certificado firmado por CA ayuda a evitar ataques de tipo "man in the middle" y proporciona una mejor protección de seguridad que un certificado autofirmado.' 
---
= Descargar una solicitud de firma de certificación HTTPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede descargar una solicitud de firma de certificación para el certificado de seguridad HTTPS actual para poder proporcionar el archivo a una entidad de certificación para firmar. Un certificado firmado por CA ayuda a evitar ataques de tipo "man in the middle" y proporciona una mejor protección de seguridad que un certificado autofirmado.

*Lo que necesitará*

Debe tener la función Administrador de aplicaciones.

.Pasos
. En el panel de navegación izquierdo, haga clic en *General* > *Certificado HTTPS*.
. Haga clic en *Descargar la solicitud de firma de certificado HTTPS*.
. Guarde la `<hostname>.csr` archivo.


Puede proporcionar el archivo a una entidad de certificación para firmar e instalar el certificado firmado.
