---
permalink: install-linux/concept_upgrade_unified_manager_on_rhel_or_centos.html 
sidebar: sidebar 
keywords: upgrade, unified manager, red hat enterprise, linux, centOS 
summary: Es posible actualizar Unified Manager cuando hay una nueva versión de software disponible. 
---
= Actualización de Unified Manager en Red Hat Enterprise Linux o CentOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible actualizar Unified Manager cuando hay una nueva versión disponible.

Los parches del software Unified Manager, que se proporcionan con NetApp, se instalan siguiendo el mismo procedimiento que las versiones nuevas.

Si Unified Manager se empareja con una instancia de OnCommand Workflow Automation y hay nuevas versiones del software disponibles para ambos productos, debe desconectar los productos y, a continuación, configurar una nueva conexión de Workflow Automation tras las actualizaciones. Si solo actualiza uno de los productos, deberá iniciar sesión en Workflow Automation tras la actualización y comprobar que aún se recopilen datos de Unified Manager.
