---
permalink: install-linux/reference_red_hat_and_centos_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: linux software, installation requirements, system, authorization,  requirements 
summary: El sistema Linux en el que instala Unified Manager requiere versiones específicas del sistema operativo y del software compatible. 
---
= Requisitos de instalación y software Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema Linux en el que instala Unified Manager requiere versiones específicas del sistema operativo y del software compatible.



== Software del sistema operativo

El sistema Linux debe tener instaladas las siguientes versiones del sistema operativo y el software de soporte:

* Red Hat Enterprise Linux versiones 8.x y 9,4, basado en la arquitectura x86_64.


Consulte la matriz de interoperabilidad para ver la lista completa y más actual de versiones compatibles de Red Hat Enterprise Linux.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"^]

El servidor debe estar dedicado a ejecutar Unified Manager. No se deben instalar otras aplicaciones en el servidor. Es posible que el escáner de vulnerabilidades como Qualys esté instalado en su sistema Linux debido a las regulaciones de la empresa. Debe deshabilitar el análisis de vulnerabilidades antes de instalar Unified Manager para evitar que falle la instalación.


NOTE: Los análisis de vulnerabilidades (como Qualys) pueden hacer que el uso de CPU sea elevado al analizar la máquina virtual (VM) de forma interna (donde Unified Manager y el escáner de vulnerabilidades están instalados en la misma máquina virtual) o externa (donde Unified Manager y el análisis de vulnerabilidades están instalados en dos servidores diferentes y el análisis de vulnerabilidades analiza la máquina virtual donde está instalado Unified Manager). Este problema suele hacer que la máquina virtual no responda y afecta a los servicios de Unified Manager. Por lo tanto, NetApp recomienda deshabilitar el análisis de vulnerabilidades en la máquina virtual donde está instalado Unified Manager. Si la desactivación del escáner no es una opción, analice la VM durante las horas no laborables y reinicie los servicios una vez que se haya completado el análisis.



== Software de terceros

Unified Manager se ha puesto en marcha en un servidor web de WildFly. WildFly 26.1.3 se incluye y configura con Unified Manager.

Se requieren los siguientes paquetes de terceros, pero no se incluyen con Unified Manager. Estos paquetes son instalados automáticamente por el `yum` instalador durante la instalación, siempre que haya configurado los repositorios como se menciona en las siguientes secciones.

* MySQL Community Edition versión 8.0.37 (desde el repositorio de MySQL).
* OpenJDK versión 11.0.23 (del repositorio de Red Hat Extra Enterprise Linux Server)
* Python 3.6.x
* P7zip versión 16.02 o posterior (del repositorio de Red Hat Extra Packages para Enterprise Linux)


[NOTE]
====
Debe apagar una instancia en ejecución de Unified Manager antes de actualizar cualquier software de terceros. Tras completar la instalación del software de terceros, puede reiniciar Unified Manager.

====


== Requisitos de autorización de usuarios

La instalación de Unified Manager en un sistema Linux puede realizarlo el usuario raíz o los usuarios no raíz mediante el `sudo` comando.



== Requisitos de instalación

A continuación se enumeran las mejores prácticas para instalar Red Hat Enterprise Linux y los repositorios asociados en el sistema. Los sistemas instalados o configurados de manera diferente, o puestos en marcha fuera de las instalaciones (en el cloud), pueden requerir pasos adicionales y es posible que Unified Manager no se ejecute correctamente en dichas puestas en marcha.

* Debe instalar Red Hat Enterprise Linux de acuerdo con las mejores prácticas de Red Hat y debe seleccionar las siguientes opciones predeterminadas, que requieren la selección del entorno base de servidor con GUI.
* Al instalar Unified Manager en Red Hat Enterprise Linux, el sistema debe tener acceso al repositorio adecuado para que el programa de instalación pueda acceder e instalar todas las dependencias de software necesarias.
* Para la `yum` Instalador para buscar software dependiente en los repositorios de Red Hat Enterprise Linux, debe haber registrado el sistema durante la instalación de Red Hat Enterprise Linux o después mediante una suscripción válida a Red Hat.
+
Consulte la documentación de Red Hat para obtener información acerca de Red Hat Subscription Manager.

* Debe habilitar el repositorio de paquetes adicionales para Enterprise Linux (EPEL) para instalar correctamente las utilidades de terceros necesarias en el sistema.
+
Si el repositorio de EPEL no está configurado en su sistema, debe descargar y configurar manualmente el repositorio.

+
Consulte link:task_manually_configure_epel_repository.html["Configurar manualmente el repositorio de EPEL"].

* Si no está instalada la versión correcta de MySQL, debe habilitar el repositorio de MySQL para que pueda instalar correctamente el software MySQL en el sistema.
+
Si el repositorio de MySQL no está configurado en el sistema, debe descargar y configurar manualmente el repositorio.

+
Consulte link:task_manually_configure_mysql_repository.html["Configurar manualmente el repositorio de MySQL"].



Si su sistema no tiene acceso a Internet y los repositorios no se duplican desde un sistema conectado a Internet al sistema no conectado, siga las instrucciones de instalación para determinar las dependencias de software externo de su sistema. A continuación, puede descargar el software que necesite en el sistema conectado a Internet y copiar `.rpm` los archivos en el sistema en el que tenga pensado instalar Unified Manager. Para descargar los artefactos y paquetes, debe usar `yum install` el comando. Debe asegurarse de que los dos sistemas ejecutan la misma versión del sistema operativo y de que la licencia de suscripción es para Red Hat Enterprise Linux correspondiente.

[NOTE]
====
No debe instalar el software de terceros necesario desde repositorios distintos a los que se enumeran aquí. El software instalado desde los repositorios de Red Hat se ha diseñado explícitamente para Red Hat Enterprise Linux y cumple con las prácticas recomendadas de Red Hat (diseños de directorios, permisos, etc.). Es posible que el software desde otras ubicaciones no siga estas directrices, lo que puede provocar errores en la instalación de Unified Manager o podría provocar problemas con actualizaciones futuras.

====


== Requisito del puerto 443

Las imágenes genéricas de Red Hat Enterprise Linux podrían bloquear el acceso externo al puerto 443. Debido a esta restricción, es posible que no se pueda conectar a la interfaz de usuario web del administrador después de instalar Unified Manager. La ejecución del siguiente comando permite el acceso al puerto 443 para todos los usuarios y aplicaciones externos en un Red Hat Enterprise Linux genérico.

`# firewall-cmd --zone=public --add-port=443/tcp --permanent; firewall-cmd --reload`

Debe instalar Red Hat Enterprise Linux con el entorno base ''Servidor con GUI''. Proporciona los comandos utilizados por las instrucciones de instalación de Unified Manager. Es posible que otros entornos base requieran instalar comandos adicionales para validar o completar la instalación. Si `firewall-cmd` no está disponible en su sistema, debe instalarlo ejecutando el siguiente comando:

`# sudo yum install firewalld`

Póngase en contacto con EL departamento de TI antes de ejecutar los comandos para ver si sus políticas de seguridad requieren un procedimiento diferente.

[NOTE]
====
THP (páginas enormes transparentes) debe desactivarse en los sistemas Red Hat. Cuando se habilita esta opción, en algunos casos puede provocar que Unified Manager se apague cuando ciertos procesos consuman demasiado memoria y queden terminados.

====