---
permalink: install-linux/task_change_jboss_password.html 
sidebar: sidebar 
keywords: change, jboss password 
summary: Puede restablecer la contraseña de JBoss específica de la instancia que se haya establecido durante la instalación. Es posible restablecer la contraseña de manera opcional; en caso de que el sitio requiera esta funcionalidad de seguridad para anular la configuración de instalación de Unified Manager. Esta operación también cambia la contraseña que JBoss utiliza para acceder a MySQL. 
---
= Cambio de la contraseña de JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede restablecer la contraseña de JBoss específica de la instancia que se haya establecido durante la instalación. Es posible restablecer la contraseña de manera opcional; en caso de que el sitio requiera esta funcionalidad de seguridad para anular la configuración de instalación de Unified Manager. Esta operación también cambia la contraseña que JBoss utiliza para acceder a MySQL.

* Debe tener acceso de usuario raíz al sistema Red Hat Enterprise Linux o CentOS en el que está instalado Unified Manager.
* Debe poder acceder a la información proporcionada por NetApp `password.sh` script en el directorio `/opt/netapp/essentials/bin`.


.Pasos
. Inicie sesión como usuario root en el sistema.
. Detenga los servicios de Unified Manager introduciendo los siguientes comandos en el orden mostrado:
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
No detenga el software MySQL asociado.

. Introduzca el siguiente comando para iniciar el proceso de cambio de contraseña:
+
`/opt/netapp/essentials/bin/password.sh resetJBossPassword`

. Cuando se le solicite, introduzca la nueva contraseña de JBoss y, a continuación, introdúzcala una segunda vez para confirmarla.
+
Tenga en cuenta que la contraseña debe tener entre 8 y 16 caracteres, y debe contener al menos un dígito, mayúsculas y minúsculas caracteres, y al menos uno de estos caracteres especiales:

+
`+!@%^*-_+=[]:<>.?/~+`

. Una vez finalizado el script, inicie los servicios de Unified Manager introduciendo los siguientes comandos en el orden que se muestra:
+
`systemctl start ocie`

+
`systemctl start ocieau`

. Después de iniciar todos los servicios, puede iniciar sesión en la interfaz de usuario de Unified Manager.

