---
permalink: install-linux/task_upgrade_host_os_from_rhel_6_x_to_7_x.html 
sidebar: sidebar 
keywords: upgrade, host OS, red hat enterprise, linux 7.x, 8.x 
summary: Si anteriormente instaló Unified Manager en un sistema Red Hat Enterprise Linux 7.x y debe actualizar a Red Hat Enterprise Linux 8.x, debe seguir uno de los procedimientos enumerados en este tema. En ambos casos, debe crear una copia de seguridad de Unified Manager en el sistema Red Hat Enterprise Linux 7.x y, a continuación, restaurar el backup en un sistema Red Hat Enterprise Linux 8.x. 
---
= Actualizar el sistema operativo del host desde Red Hat Enterprise Linux 7.x a 8.x.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si anteriormente instaló Unified Manager en un sistema Red Hat Enterprise Linux 7.x y debe actualizar a Red Hat Enterprise Linux 8.x, debe seguir uno de los procedimientos enumerados en este tema. En ambos casos, debe crear una copia de seguridad de Unified Manager en el sistema Red Hat Enterprise Linux 7.x y, a continuación, restaurar el backup en un sistema Red Hat Enterprise Linux 8.x.

La diferencia entre las dos opciones que se muestran a continuación es que, en un caso, se está ejecutando la restauración de Unified Manager en un nuevo servidor 8.x y, en el otro caso, se está realizando la operación de restauración en el mismo servidor.

Dado que esta tarea requiere que se cree un backup de Unified Manager en el sistema Red Hat Enterprise Linux 7.x, debe crear el backup solo cuando esté preparado para completar todo el proceso de actualización de modo que Unified Manager no tenga conexión durante el menor período de tiempo posible. Las brechas en los datos recopilados se muestran en la interfaz de usuario de Unified Manager durante el periodo de tiempo durante el cual se apaga el sistema Red Hat Enterprise Linux 7.x y antes de que se inicie la nueva versión de Red Hat Enterprise Linux 8.x.

Consulte la Ayuda en línea de _Active IQ Unified Manager_ si necesita revisar instrucciones detalladas para los procesos de copia de seguridad y restauración.

*Actualización del sistema operativo host mediante un nuevo servidor*

Siga estos pasos si tiene un sistema de repuesto en el que puede instalar el software Red Hat Enterprise Linux 8.x para poder realizar la restauración de Unified Manager en ese sistema mientras el sistema Red Hat Enterprise Linux 7.x sigue estando disponible.

. Instale y configure un servidor nuevo con el software Red Hat Enterprise Linux 8.x.
+
Consulte link:reference_red_hat_and_centos_software_and_installation_requirements.html["Requisitos de instalación y software Linux"].

. En el sistema Red Hat Enterprise Linux 8.x, instale la misma versión del software Unified Manager que tiene en el sistema Red Hat Enterprise Linux 7.x.
+
Consulte link:concept_install_unified_manager_on_rhel_or_centos.html["Instalación de Unified Manager en Linux"].

+
No inicie la interfaz de usuario ni configure ningún clúster, usuario ni configuración de autenticación cuando se complete la instalación. El archivo de backup rellena esta información durante el proceso de restauración.

. En el sistema Red Hat Enterprise Linux 7.x, desde el menú Administration de la interfaz de usuario web, cree un backup de Unified Manager y, a continuación, copie el archivo de backup (`.7z` archivo) y el contenido del directorio del repositorio de la base de datos (`/database-dumps-repo` subdirectorio) a una ubicación externa.
. En el sistema Red Hat Enterprise Linux 7.x, apague Unified Manager.
. En el sistema Red Hat Enterprise Linux 8.x, copie el archivo de copia de seguridad (`.7z` archivo) desde la ubicación externa a. `/opt/netapp/data/ocum-backup/` y los archivos del repositorio de la base de datos en `/database-dumps-repo` subdirectorio bajo el `/ocum-backup` directorio.
. Introduzca el siguiente comando para restaurar la base de datos de Unified Manager desde el archivo de backup:
+
`um backup restore -f /opt/netapp/data/ocum-backup/<backup_file_name>`

. Introduzca la dirección IP o la URL en el explorador web para iniciar la interfaz de usuario web de Unified Manager y, a continuación, inicie sesión en el sistema.


Una vez que haya comprobado que el sistema funciona correctamente, puede eliminar Unified Manager del sistema Red Hat Enterprise Linux 7.x.

*Actualización del sistema operativo host en el mismo servidor*

Siga estos pasos si no dispone de un sistema de repuesto en el que puede instalar el software Red Hat Enterprise Linux 8.x.

. En el menú Administration de la interfaz de usuario web, cree un backup de Unified Manager y, a continuación, copie el archivo de backup (`.7z` archivo) y el contenido del directorio del repositorio de la base de datos (`/database-dumps-repo` subdirectorio) a una ubicación externa.
. Retire la imagen de Red Hat Enterprise Linux 7.x del sistema y límpiela por completo.
. Instale y configure el software Red Hat Enterprise Linux 8.x en el mismo sistema.
+
Consulte link:reference_red_hat_and_centos_software_and_installation_requirements.html["Requisitos de instalación y software Linux"].

. En el sistema Red Hat Enterprise Linux 8.x, instale la misma versión del software Unified Manager que tenía en el sistema Red Hat Enterprise Linux 7.x.
+
Consulte link:concept_install_unified_manager_on_rhel_or_centos.html["Instalación de Unified Manager en Linux"].

+
No inicie la interfaz de usuario ni configure ningún clúster, usuario ni configuración de autenticación cuando se complete la instalación. El archivo de backup rellena esta información durante el proceso de restauración.

. Copie el archivo de copia de seguridad (`.7z` archivo) desde la ubicación externa a. `/opt/netapp/data/ocum-backup/` y los archivos del repositorio de la base de datos en `/database-dumps-repo` subdirectorio bajo el `/ocum-backup` directorio.
. Introduzca el siguiente comando para restaurar la base de datos de Unified Manager desde el archivo de backup:
+
`um backup restore -f /opt/netapp/data/ocum-backup/<backup_file_name>`

. Introduzca la dirección IP o la URL en el explorador web para iniciar la interfaz de usuario web de Unified Manager y, a continuación, inicie sesión en el sistema.

