---
permalink: include/upgrade-path.html 
sidebar: sidebar 
keywords: supported upgrade path, upgrade path, n-2, which versions can be upgraded 
summary: Ruta de actualización admitida 
---
= La ruta de actualización compatible con las versiones de Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager admite una ruta de actualización específica para cada versión.

No todas las versiones de Unified Manager pueden realizar una actualización local a versiones posteriores.  Las actualizaciones de Unified Manager están limitadas a un modelo N-2.  Esto significa que solo podrás realizar una actualización a las próximas dos versiones en todas las plataformas.  Por ejemplo, puede realizar una actualización a Unified Manager 9.18 desde Unified Manager 9.14 y 9.16 únicamente.

Si ejecuta una versión anterior a las versiones compatibles, primero deberá actualizar la instancia de Unified Manager con una de las versiones compatibles y, a continuación, actualizarla a la versión actual.

Por ejemplo, si la versión instalada es Unified Manager 9,9 y desea actualizar a Unified Manager 9,14, debe seguir una secuencia de actualizaciones.

.Ruta de actualización de ejemplo:
. Actualización 9,11 -> 9,13
. Actualización 9,13 -> 9,14
. Actualización 9,13 -> 9,16
. Actualización 9.14 o 9.16 -> 9.18


Para obtener más información acerca de la matriz de rutas de actualización, consulte este tema https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_the_upgrade_path_for_Active_IQ_Unified_Manager_versions["Artículo de la base de conocimientos (KB)"].
