---
permalink: events/reference_management_station_events.html 
sidebar: sidebar 
keywords: management, station, events, impact area, configuration, performance 
summary: Los eventos de la estación de gestión le proporcionan información sobre el estado del servidor en el que está instalado Unified Manager para poder supervisar posibles problemas. Los eventos se agrupan por área de impacto e incluyen el nombre del evento y de captura, el nivel de impacto, el tipo de origen y la gravedad. 
---
= Eventos de la estación de gestión
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los eventos de la estación de gestión le proporcionan información sobre el estado del servidor en el que está instalado Unified Manager para poder supervisar posibles problemas. Los eventos se agrupan por área de impacto e incluyen el nombre del evento y de captura, el nivel de impacto, el tipo de origen y la gravedad.



== Área de impacto: Configuración

|===
| Nombre del evento (nombre de la captura) | Nivel de impacto | Tipo de origen | Gravedad 


 a| 
Espacio en disco del servidor de gestión casi completo (ocumEvtUnifiedManagerDiskNearSpacelyFull)
 a| 
Riesgo
 a| 
Estación de gestión
 a| 
Advertencia



 a| 
Espacio completo en disco del servidor de administración (ocumEvtUnifiedManagerDiskSpaceFull)
 a| 
Incidente
 a| 
Estación de gestión
 a| 
Crítico



 a| 
Memoria de servidor de administración baja (ocumEvtUnifiedManagerMemoryLow)
 a| 
Riesgo
 a| 
Estación de gestión
 a| 
Advertencia



 a| 
Servidor de administración casi sin memoria (ocumEvtUnifiedManagerMemoriaAlmostOut)
 a| 
Incidente
 a| 
Estación de gestión
 a| 
Crítico



 a| 
Se ha aumentado el tamaño del archivo de registro de MySQL; se requiere un reinicio (ocumEvtMysqlLogFileSizeWarning)
 a| 
Incidente
 a| 
Estación de gestión
 a| 
Advertencia



 a| 
La asignación de tamaño total de registro de auditoría está a cerca de estar lleno
 a| 
Riesgo
 a| 
Estación de gestión
 a| 
Advertencia



 a| 
Certificado de servidor de syslog a punto de expirar
 a| 
Riesgo
 a| 
Estación de gestión
 a| 
Advertencia



 a| 
El certificado de servidor de syslog caducó
 a| 
Riesgo
 a| 
Estación de gestión
 a| 
Error



 a| 
Archivo de registro de auditoría alterado
 a| 
Riesgo
 a| 
Estación de gestión
 a| 
Advertencia



 a| 
Se eliminó el archivo de registro de auditoría
 a| 
Riesgo
 a| 
Estación de gestión
 a| 
Advertencia



 a| 
Error de conexión del servidor de syslog
 a| 
Riesgo
 a| 
Estación de gestión
 a| 
Error



 a| 
Se cambió la configuración del servidor de syslog
 a| 
Evento
 a| 
Estación de gestión
 a| 
Advertencia

|===


== Área de impacto: Rendimiento

|===
| Nombre del evento (nombre de la captura) | Nivel de impacto | Tipo de origen | Gravedad 


 a| 
El análisis de datos de rendimiento se ve afectado(ocumEvtUnifiedManagerDataMissingAnalyze)
 a| 
Riesgo
 a| 
Estación de gestión
 a| 
Advertencia



 a| 
La recopilación de datos de rendimiento se ve afectada (ocumEvtUnifiedManagerDataMissingCollection)
 a| 
Incidente
 a| 
Estación de gestión
 a| 
Crítico

|===
[NOTE]
====
Estos dos últimos eventos de rendimiento solo estaban disponibles para Unified Manager 7.2. Si alguno de estos eventos se encuentra en el estado New y se actualiza a una versión más reciente del software Unified Manager, los eventos no se depuran automáticamente. Deberá mover los eventos al estado Resolved manualmente.

====