---
permalink: events/task_assign_events_to_specific_users.html 
sidebar: sidebar 
keywords: assign, events, specific, users 
summary: Puede asignar eventos sin asignar a usted mismo o a otros usuarios, incluidos los usuarios remotos. Puede reasignar eventos asignados a otro usuario, si es necesario. Por ejemplo, cuando ocurren problemas frecuentes en un objeto de almacenamiento, puede asignar los eventos para estos problemas al usuario que gestiona ese objeto. 
---
= Asignar eventos a usuarios específicos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede asignar eventos sin asignar a usted mismo o a otros usuarios, incluidos los usuarios remotos. Puede reasignar eventos asignados a otro usuario, si es necesario. Por ejemplo, cuando ocurren problemas frecuentes en un objeto de almacenamiento, puede asignar los eventos para estos problemas al usuario que gestiona ese objeto.

*Lo que necesitará*

* El nombre del usuario y el ID de correo electrónico deben estar configurados correctamente.
* Debe tener el rol de operador, administrador de aplicaciones o administrador de almacenamiento.


.Pasos
. En el panel de navegación izquierdo, haga clic en *Gestión de eventos*.
. En la página de inventario *Event Management*, seleccione uno o más eventos que desee asignar.
. Asigne el evento seleccionando una de las siguientes opciones:
+
|===
| Si desea asignar el evento a... | Realice lo siguiente... 


 a| 
Usted mismo
 a| 
Haga clic en *asignar a* > *Me*.



 a| 
Otro usuario
 a| 
.. Haga clic en *asignar a* > *otro usuario*.
.. En el cuadro de diálogo asignar propietario, introduzca el nombre de usuario o seleccione un usuario de la lista desplegable.
.. Haga clic en *asignar*.
+
Se envía una notificación por correo electrónico al usuario.

+
[NOTE]
====
Si no introduce un nombre de usuario o selecciona un usuario de la lista desplegable y hace clic en *asignar*, el evento permanece sin asignar.

====


|===

