---
permalink: data-protection/task_remove_aggregates_from_resource_pools.html 
sidebar: sidebar 
keywords: remove, aggregates, resource pools 
summary: 'Es posible quitar agregados de un pool de recursos existente: Por ejemplo, cuando se desea usar un agregado con otro fin.' 
---
= Eliminación de agregados de pools de recursos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible quitar agregados de un pool de recursos existente: Por ejemplo, cuando se desea usar un agregado con otro fin.

*Lo que necesitará*

Debe tener el rol de administrador de aplicaciones o de administrador del almacenamiento.

Los miembros del pool de recursos solo se muestran cuando se selecciona un pool de recursos.

.Pasos
. En el panel de navegación izquierdo, haga clic en *Protección* > *agrupaciones de recursos*.
. Seleccione el pool de recursos del que desea quitar agregados miembros.
+
La lista de agregados de miembros se muestra en el panel Miembros.

. Seleccione uno o varios agregados.
+
El botón *Quitar* está activado.

. Haga clic en *Quitar.*
+
Aparecerá un cuadro de diálogo de advertencia.

. Haga clic en *Sí* para continuar.
+
Los agregados seleccionados se eliminan del panel Miembros.


