---
permalink: data-protection/task_reverse_protection_relationships.html 
sidebar: sidebar 
keywords: reverse, protection, relationships, volume, relationships page 
summary: Cuando un desastre deshabilita el volumen de origen en la relación de protección, es posible utilizar el volumen de destino para suministrar datos mediante la conversión a un volumen de lectura/escritura mientras se repara o sustituye el origen. Cuando el origen vuelve a estar disponible para recibir datos, puede utilizar la operación de resincronización inversa para establecer la relación en la dirección inversa y sincronizar los datos del origen con los datos en el destino de lectura/escritura. 
---
= Inversión de las relaciones de protección en la página Volume Relationships
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando un desastre deshabilita el volumen de origen en la relación de protección, es posible utilizar el volumen de destino para suministrar datos mediante la conversión a un volumen de lectura/escritura mientras se repara o sustituye el origen. Cuando el origen vuelve a estar disponible para recibir datos, puede utilizar la operación de resincronización inversa para establecer la relación en la dirección inversa y sincronizar los datos del origen con los datos en el destino de lectura/escritura.

*Lo que necesitará*

* Debe tener el rol de administrador de aplicaciones o de administrador del almacenamiento.
* Debe haber configurado Workflow Automation.
* La relación no debe ser una relación de SnapVault.
* Debe haber una relación de protección.
* La relación de protección debe romperse.
* El origen y el destino deben estar en línea.
* El origen no debe ser el destino de otro volumen de protección de datos.
* Cuando realiza esta tarea, se eliminan los datos en el origen más nuevos que los de la copia Snapshot común.
* Las políticas y las programaciones creadas en relaciones de resincronización inversa son las mismas que en la relación de protección original.
+
Si no existen las políticas y las programaciones, se crean.



.Pasos
. En la página *Relaciones de volumen*, seleccione uno o más volúmenes con relaciones que desee invertir y, en la barra de herramientas, haga clic en *Resync inversa*.
+
Se muestra el cuadro de diálogo Reverse Resync.

. Compruebe que las relaciones que aparecen en el cuadro de diálogo *Resync inversa* son las que desea realizar la operación de resincronización inversa y, a continuación, haga clic en *Enviar*.
+
Se inicia la operación de resincronización inversa, vuelve a la página Relaciones de volumen y se muestra un enlace de trabajos en la parte superior de la página.

. *Opcional:* haga clic en *Ver trabajos* en la página *Relaciones de volumen* para realizar un seguimiento del estado de cada trabajo de resincronización inversa.
+
Se muestra una lista filtrada de trabajos relacionados con esta operación.

. *Opcional:* haga clic en la flecha *Atrás* de su navegador para volver a la página *Relaciones de volumen*.
+
La operación de resincronización inversa se completa cuando todas las tareas de trabajo se completan correctamente.


