---
permalink: data-protection/task_break_snapmirror_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: break, snapmirror, relationship, volume, health details 
summary: Es posible interrumpir una relación de protección en la página de detalles Volume/Health y detener las transferencias de datos entre un volumen de origen y un volumen de destino en una relación de SnapMirror. Puede romper una relación cuando desea migrar datos, para la recuperación ante desastres o para la prueba de aplicaciones. El volumen de destino se cambia a un volumen de lectura/escritura. No es posible interrumpir una relación de SnapVault. 
---
= Romper una relación de SnapMirror en la página de detalles Volume/Health
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible interrumpir una relación de protección en la página de detalles Volume/Health y detener las transferencias de datos entre un volumen de origen y un volumen de destino en una relación de SnapMirror. Puede romper una relación cuando desea migrar datos, para la recuperación ante desastres o para la prueba de aplicaciones. El volumen de destino se cambia a un volumen de lectura/escritura. No es posible interrumpir una relación de SnapVault.

*Lo que necesitará*

* Debe tener el rol de administrador de aplicaciones o de administrador del almacenamiento.
* Debe haber configurado Workflow Automation.


.Pasos
. En la pestaña *Protección* de la página de detalles *volumen / Salud*, seleccione en la topología la relación de SnapMirror que desea romper.
. Haga clic con el botón derecho del ratón en el destino y seleccione *romper* en el menú.
+
Se muestra el cuadro de diálogo romper relación.

. Haga clic en *continuar* para romper la relación.
. En la topología, compruebe que la relación está rota.

