---
permalink: data-protection/task_remove_protection_relationship_voldtls.html 
sidebar: sidebar 
keywords: remove, protection, relationship,  volume, health details page 
summary: 'Puede quitar una relación de protección para eliminar de forma permanente una relación existente entre el origen y el destino seleccionados: Por ejemplo, cuando desea crear una relación con otro destino. Esta operación elimina todos los metadatos y no puede deshacerse.' 
---
= Eliminación de una relación de protección de la página de detalles Volume / Health
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede quitar una relación de protección para eliminar de forma permanente una relación existente entre el origen y el destino seleccionados: Por ejemplo, cuando desea crear una relación con otro destino. Esta operación elimina todos los metadatos y no puede deshacerse.

*Lo que necesitará*

* Debe tener el rol de administrador de aplicaciones o de administrador del almacenamiento.
* Debe haber configurado Workflow Automation.


.Pasos
. En la ficha *Protección* de la página de detalles *volumen / Estado*, seleccione en la topología la relación de SnapMirror que desee eliminar.
. Haga clic con el botón derecho del ratón en el nombre del destino y seleccione *Quitar* en el menú.
+
Se muestra el cuadro de diálogo Eliminar relación.

. Haga clic en *continuar* para eliminar la relación.
+
La relación se elimina de la página de detalles Volume/Health.


