---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volumes.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship, health, volumes view 
summary: 'Con la vista Estado: Todos los volúmenes, es posible crear varias relaciones de protección de SnapMirror a la vez. Para ello, se seleccionan más de un volumen en la misma máquina virtual de almacenamiento.' 
---
= Crear una relación de protección de SnapMirror desde la vista Estado: Todos los volúmenes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Con la vista Estado: Todos los volúmenes, es posible crear varias relaciones de protección de SnapMirror a la vez. Para ello, se seleccionan más de un volumen en la misma máquina virtual de almacenamiento.

*Lo que necesitará*

* Debe tener el rol de administrador de aplicaciones o de administrador del almacenamiento.
* Debe haber configurado Workflow Automation.


El menú *Protect* no aparece en los siguientes casos:

* Si la configuración de RBAC no permite esta acción: Por ejemplo, si solo tiene privilegios de operador
* Cuando se desconoce el ID de volumen: Por ejemplo, cuando se mantiene una relación de interconexión de clústeres y el clúster de destino aún no se detectó


.Pasos
. En la vista *Estado: Todos los volúmenes*, seleccione el volumen que desea proteger.
+
Como alternativa, para crear varias relaciones de protección en el mismo SVM, seleccione uno o más volúmenes en la vista Estado: Todos los volúmenes y haga clic en *proteger* > *SnapMirror* en la barra de herramientas.

+
Se muestra el cuadro de diálogo Configurar protección.

. Haga clic en *SnapMirror* para ver la ficha *SnapMirror* y configurar la información de destino.
. Haga clic en *Avanzado* para establecer la garantía de espacio según sea necesario y, a continuación, haga clic en *aplicar*.
. Complete el área *Información de destino* y el área *Configuración de relación* de la ficha *SnapMirror*.
. Haga clic en *aplicar*.
+
Se devuelve a la vista Health: Todos los volúmenes.

. Haga clic en el enlace del trabajo de configuración de protección en la parte superior de la vista * Estado: Todos los volúmenes*.
+
Si solo se crea una relación de protección, se muestra la página de detalles Job; sin embargo, si se crea más de una relación de protección, se muestra una lista de todos los trabajos asociados con la operación de protección.

. Debe realizar una de las siguientes acciones:
+
** Si sólo tiene un trabajo, haga clic en *Actualizar* para actualizar la lista de tareas y los detalles de tareas asociados con el trabajo de configuración de protección y para determinar cuándo se ha completado el trabajo.
** Si tiene más de un trabajo:
+
... Haga clic en un trabajo de la lista trabajos.
... Haga clic en *Actualizar* para actualizar la lista de tareas y los detalles de tareas asociados con el trabajo de configuración de protección y para determinar cuándo se ha completado el trabajo.
... Utilice el botón *Atrás* para volver a la lista filtrada y ver otro trabajo.






En función de la SVM de destino especificada durante la configuración o de las opciones habilitadas en su configuración avanzada, la relación de SnapMirror resultante puede ser una de varias variaciones posibles:

* Si especificó una SVM de destino que se ejecuta con la misma versión o una posterior de ONTAP en comparación con la del volumen de origen, el resultado predeterminado será una relación de SnapMirror basada en replicación de bloques.
* Si especificó una SVM de destino que se ejecuta con una misma versión o una más reciente de ONTAP en comparación con la del volumen de origen, pero habilitó la replicación de versión flexible en la configuración avanzada, se obtiene una relación de SnapMirror con la replicación de versión flexible.
* Si especificó una SVM de destino que se ejecuta con una versión de ONTAP anterior a la del volumen de origen y la versión anterior admite la replicación de versión flexible, el resultado es una relación de SnapMirror con la replicación de versión flexible.

